// scada-frontend/src/components/LivePanel.vue
<script setup>
/**
 * LivePanel — a single self-polling tile in the Live dashboard grid.
 *
 * Renders one or more tag/device "connections" in a configurable Grafana-style
 * visualization: time series, bar, stat, gauge, bar gauge, histogram or table.
 * Tag-source panels can plot MULTIPLE tags at once (panel.options.tags) — each
 * tag becomes its own coloured series. The per-viz parameters (min/max,
 * thresholds, decimals, orientation, …) come from `panel.options`. Streams a
 * sliding-window series per tag, refreshing every poll interval. Admins see
 * Edit / Delete controls in the header.
 */
import { ref, computed, watch, onMounted, onBeforeUnmount } from 'vue'
import VChart from 'vue-echarts'
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { LineChart, BarChart, GaugeChart } from 'echarts/charts'
import { GridComponent, TooltipComponent, LegendComponent } from 'echarts/components'
import { fetchSeries, fetchLatest } from '@/api/readings'
import { fetchTagLatest } from '@/api/tags'
import { fetchSchemaLatest, fetchSchemaSeries } from '@/api/schema'
import { SERIES_PALETTE, colorAt } from '@/utils/seriesPalette'
import { compileExpr, applyExpr } from '@/utils/mathExpr'

use([CanvasRenderer, LineChart, BarChart, GaugeChart, GridComponent, TooltipComponent, LegendComponent])

const WARN_COLOR = '#e6a23c'
const CRIT_COLOR = '#f56c6c'

const props = defineProps({
  panel: { type: Object, required: true },
  deviceName: { type: String, default: '' },
  canManage: { type: Boolean, default: false },
})

const emit = defineEmits(['edit', 'duplicate', 'delete', 'poll-interval-change', 'updated'])

// Poll interval selector — values are seconds, kept in sync with backend whitelist.
const POLL_INTERVALS = [
  { value: 5, label: '5s' },
  { value: 30, label: '30s' },
  { value: 60, label: '1m' },
  { value: 600, label: '10m' },
  { value: 1800, label: '30m' },
  { value: 3600, label: '1h' },
]

const pollSeconds = computed(() => props.panel.poll_interval_seconds || 5)
const isTag = computed(() => props.panel.source === 'tag')
const isTable = computed(() => props.panel.source === 'table')

// Table source: filter values chosen in the editor become the series. When no
// filter column is set the panel is a single series labelled by its value column.
const tableFilters = computed(() => {
  const f = props.panel.options?.filters
  return Array.isArray(f) ? f.filter(Boolean) : []
})
const tableHasFilter = computed(() => !!props.panel.filter_col && tableFilters.value.length > 0)
// Map a series key to the filter value sent to the API (null = no WHERE filter).
const tableFilterVal = (key) => (tableHasFilter.value ? key : null)

function onPollIntervalSelect(v) {
  emit('poll-interval-change', props.panel, v)
}

// Per-series data, keyed by series key (tag name for tag source, metric for
// device source). Reassigned immutably so ECharts' :option recomputes & repaints.
const seriesPoints = ref({}) // { [key]: [[epochMs, value], ...] }
const seriesLatest = ref({}) // { [key]: { value, ts } }
const unit = ref('')
const error = ref('')

let timer = null

// Normalize legacy "line" panels to the time-series renderer.
const vizType = computed(() => (props.panel.chart_type === 'line' ? 'timeseries' : props.panel.chart_type))
const opts = computed(() => props.panel.options || {})

// The series keys for this panel: the tag list (tag source), the filter values
// (table source), or the single metric (device source / unfiltered table).
const seriesTags = computed(() => {
  if (isTag.value) {
    const tags = props.panel.options?.tags
    const list = Array.isArray(tags) && tags.length
      ? tags
      : (props.panel.tag_name ? [props.panel.tag_name] : [])
    return list.filter(Boolean)
  }
  if (isTable.value && tableHasFilter.value) {
    return tableFilters.value
  }
  return props.panel.metric ? [props.panel.metric] : []
})

// Hydrated view model for the renderers: one entry per series with its colour.
const seriesList = computed(() =>
  seriesTags.value.map((key, i) => ({
    key,
    label: key,
    color: colorAt(i),
    points: seriesPoints.value[key] || [],
    latest: seriesLatest.value[key] || null,
  })),
)

const isMulti = computed(() => seriesList.value.length > 1)

const isGeneric = computed(() => ['timeseries', 'bar', 'histogram', 'bargauge'].includes(vizType.value))
const showHeaderValue = computed(() => ['timeseries', 'bar', 'histogram'].includes(vizType.value))

const firstLatest = computed(() => seriesLatest.value[seriesTags.value[0]] || null)

// Per-panel math transform: applied to every reading at ingest time so all
// renderers (and warn/crit thresholds) see post-transform numbers.
const mathFn = computed(() => compileExpr(props.panel.options?.mathExpr || '').fn)

function fmt(v) {
  if (v == null) return '—'
  const d = opts.value.decimals
  return d == null ? `${v}` : Number(v).toFixed(d)
}

// Threshold → colour. warn/crit are "value ≥" cut-offs; otherwise the series base.
function thColor(v, base = colorAt(0)) {
  const { warn, crit } = opts.value
  if (crit != null && v >= crit) return CRIT_COLOR
  if (warn != null && v >= warn) return WARN_COLOR
  return base
}

// --- Shared ECharts fragments ----------------------------------------------
function legendCfg() {
  return isMulti.value
    ? { type: 'scroll', top: 0, textStyle: { color: '#8a99b3', fontSize: 10 }, itemWidth: 10, itemHeight: 10 }
    : undefined
}
const gridTop = () => (isMulti.value ? 30 : 12)
const timeAxis = () => ({ type: 'time', axisLine: { lineStyle: { color: 'rgba(255,255,255,0.12)' } }, axisLabel: { color: '#8a99b3', fontSize: 10 }, splitLine: { show: false } })
const valueAxis = () => ({ type: 'value', scale: true, axisLine: { show: false }, axisLabel: { color: '#8a99b3', fontSize: 10 }, splitLine: { lineStyle: { color: 'rgba(255,255,255,0.06)' } } })
const tooltipAxis = () => ({ trigger: 'axis', backgroundColor: '#172238', borderColor: '#172238', textStyle: { color: '#e6edf7' }, valueFormatter: (v) => `${fmt(v)} ${unit.value}` })

// --- Per-type ECharts option ----------------------------------------------
function timeseriesOption() {
  return {
    color: SERIES_PALETTE,
    legend: legendCfg(),
    grid: { top: gridTop(), right: 14, bottom: 26, left: 46 },
    tooltip: tooltipAxis(),
    xAxis: timeAxis(),
    yAxis: valueAxis(),
    series: seriesList.value.map((s, i) => ({
      name: s.label,
      type: 'line',
      smooth: opts.value.smooth !== false,
      // Show a marker while the series has a single point so the latest reading
      // is visible instantly on refresh; symbols auto-hide once it's a line.
      showSymbol: s.points.length <= 1,
      symbolSize: 6,
      lineStyle: { width: opts.value.lineWidth || 2, color: colorAt(i) },
      // Skip area fills when overlaying multiple series (muddy when stacked).
      areaStyle: opts.value.area === false || isMulti.value ? undefined : { opacity: 0.1, color: colorAt(i) },
      data: s.points,
    })),
  }
}

function barOption() {
  return {
    color: SERIES_PALETTE,
    legend: legendCfg(),
    grid: { top: gridTop(), right: 14, bottom: 26, left: 46 },
    tooltip: tooltipAxis(),
    xAxis: timeAxis(),
    yAxis: valueAxis(),
    series: seriesList.value.map((s, i) => ({
      name: s.label,
      type: 'bar',
      itemStyle: { color: colorAt(i), borderRadius: [2, 2, 0, 0] },
      data: s.points,
    })),
  }
}

// Bar gauge: one labelled, coloured bar per series (a "row" per tag).
function barGaugeOption() {
  const min = Number(opts.value.min ?? 0)
  const max = Number(opts.value.max ?? 100)
  const vertical = opts.value.orientation === 'vertical'
  const list = seriesList.value
  const data = list.map((s, i) => {
    const v = s.latest?.value ?? min
    return {
      value: v,
      itemStyle: { color: thColor(v, colorAt(i)), borderRadius: 4 },
      label: { show: true, position: vertical ? 'top' : 'right', color: '#e6edf7', fontSize: 12, formatter: () => `${fmt(v)} ${unit.value}` },
    }
  })
  const vAxis = { type: 'value', min, max, axisLabel: { color: '#8a99b3', fontSize: 10 }, splitLine: { lineStyle: { color: 'rgba(255,255,255,0.06)' } } }
  const cAxis = { type: 'category', data: list.map((s) => s.label), axisLabel: { show: isMulti.value, color: '#8a99b3', fontSize: 10 }, axisLine: { show: false }, axisTick: { show: false } }
  return {
    grid: { top: 16, bottom: 24, left: 16, right: 56, containLabel: true },
    tooltip: { backgroundColor: '#172238', borderColor: '#172238', textStyle: { color: '#e6edf7' } },
    xAxis: vertical ? cAxis : vAxis,
    yAxis: vertical ? vAxis : cAxis,
    series: [{ type: 'bar', barWidth: isMulti.value ? '55%' : '45%', data }],
  }
}

// Histogram: shared bucket range across every series, one coloured bar set each.
function histogramOption() {
  const all = seriesList.value.flatMap((s) => s.points.map((p) => p[1]))
  const n = Math.max(2, Number(opts.value.buckets ?? 20))
  let lo = Math.min(...all)
  let hi = Math.max(...all)
  if (!isFinite(lo) || !isFinite(hi) || lo === hi) {
    hi = (lo || 0) + 1
    lo = lo || 0
  }
  const width = (hi - lo) / n
  const labels = Array.from({ length: n }, (_, i) => fmt(lo + i * width))
  const series = seriesList.value.map((s, i) => {
    const counts = new Array(n).fill(0)
    for (const x of s.points.map((p) => p[1])) {
      let bi = Math.floor((x - lo) / width)
      if (bi >= n) bi = n - 1
      if (bi < 0) bi = 0
      counts[bi] += 1
    }
    return { name: s.label, type: 'bar', itemStyle: { color: colorAt(i), borderRadius: [2, 2, 0, 0] }, data: counts }
  })
  return {
    color: SERIES_PALETTE,
    legend: legendCfg(),
    grid: { top: gridTop(), right: 14, bottom: 30, left: 40 },
    tooltip: { trigger: 'axis', backgroundColor: '#172238', borderColor: '#172238', textStyle: { color: '#e6edf7' } },
    xAxis: { type: 'category', data: labels, axisLabel: { color: '#8a99b3', fontSize: 9, interval: Math.ceil(n / 8) }, axisLine: { lineStyle: { color: 'rgba(255,255,255,0.12)' } } },
    yAxis: { type: 'value', axisLabel: { color: '#8a99b3', fontSize: 10 }, splitLine: { lineStyle: { color: 'rgba(255,255,255,0.06)' } } },
    series,
  }
}

// Gauge: rendered as small multiples (one radial gauge per series).
function gaugeOptionFor(s, i) {
  const min = Number(opts.value.min ?? 0)
  const max = Number(opts.value.max ?? 100)
  const span = max - min || 1
  const color = colorAt(i)
  const { warn, crit } = opts.value
  const stops = []
  if (warn != null) stops.push([(warn - min) / span, color])
  if (crit != null) stops.push([(crit - min) / span, warn != null ? WARN_COLOR : color])
  stops.push([1, crit != null ? CRIT_COLOR : warn != null ? WARN_COLOR : color])
  const val = s.latest?.value ?? min
  const pc = thColor(val, color)
  return {
    series: [{
      type: 'gauge', min, max, radius: '92%', center: ['50%', '58%'],
      axisLine: { lineStyle: { width: 10, color: stops } },
      progress: { show: false },
      pointer: { width: 4, itemStyle: { color: pc } },
      axisTick: { show: false },
      splitLine: { length: 10, lineStyle: { color: 'rgba(255,255,255,0.25)' } },
      axisLabel: { color: '#8a99b3', fontSize: 9, distance: 12 },
      anchor: { show: true, size: 8, itemStyle: { color: pc } },
      detail: { valueAnimation: true, formatter: (v) => `${fmt(v)} ${unit.value}`, color: '#e6edf7', fontSize: isMulti.value ? 14 : 18, offsetCenter: [0, '78%'] },
      data: [{ value: val }],
    }],
  }
}

function sparklineOptionFor(s, i) {
  const color = colorAt(i)
  return {
    grid: { top: 4, right: 4, bottom: 4, left: 4 },
    xAxis: { type: 'time', show: false },
    yAxis: { type: 'value', scale: true, show: false },
    series: [{ type: 'line', smooth: true, showSymbol: s.points.length <= 1, symbolSize: 5, lineStyle: { width: 2, color }, areaStyle: { opacity: 0.15, color }, data: s.points }],
  }
}

const option = computed(() => {
  switch (vizType.value) {
    case 'bar': return barOption()
    case 'bargauge': return barGaugeOption()
    case 'histogram': return histogramOption()
    default: return timeseriesOption()
  }
})

// --- Table rows (one value column per series) ------------------------------
const tableRows = computed(() => {
  const max = Math.max(1, Number(opts.value.maxRows ?? 10))
  const cols = seriesList.value
  const longest = cols.reduce((m, s) => Math.max(m, s.points.length), 0)
  const rows = []
  for (let k = 0; k < Math.min(max, longest); k++) {
    const cells = cols.map((s) => {
      const p = s.points[s.points.length - 1 - k]
      return p ? fmt(p[1]) : '—'
    })
    let t = ''
    for (const s of cols) {
      const p = s.points[s.points.length - 1 - k]
      if (p) { t = new Date(p[0]).toLocaleTimeString(); break }
    }
    rows.push({ t, cells })
  }
  return rows
})

// --- Polling ---------------------------------------------------------------
function trimWindow(arr) {
  const cutoff = Date.now() - props.panel.window_minutes * 60_000
  return arr.filter(([t]) => t >= cutoff)
}

async function seed() {
  if (isTag.value) {
    // status_tag has no native history — start empty, accumulate via polling.
    const init = {}
    for (const t of seriesTags.value) init[t] = []
    seriesPoints.value = init
    seriesLatest.value = {}
    unit.value = ''
    await poll()
    return
  }
  if (isTable.value) {
    unit.value = ''
    // With a timestamp column we can seed real history; otherwise start empty
    // and let polling accumulate (like the tag source).
    if (!props.panel.ts_col) {
      const init = {}
      for (const k of seriesTags.value) init[k] = []
      seriesPoints.value = init
      seriesLatest.value = {}
      await poll()
      return
    }
    const fn = mathFn.value
    const results = await Promise.allSettled(
      seriesTags.value.map((k) =>
        fetchSchemaSeries({
          table: props.panel.table_name,
          valueCol: props.panel.metric,
          tsCol: props.panel.ts_col,
          filterCol: props.panel.filter_col,
          filterVal: tableFilterVal(k),
          minutes: props.panel.window_minutes,
        }),
      ),
    )
    const nextPoints = {}
    const nextLatest = {}
    results.forEach((res, i) => {
      const key = seriesTags.value[i]
      nextPoints[key] = []
      if (res.status !== 'fulfilled') return
      const arr = res.value.points.map((p) => [new Date(p.ts).getTime(), applyExpr(fn, p.value)])
      nextPoints[key] = arr
      if (arr.length) {
        const last = res.value.points[res.value.points.length - 1]
        nextLatest[key] = { value: applyExpr(fn, last.value), ts: last.ts }
      }
    })
    seriesPoints.value = nextPoints
    seriesLatest.value = nextLatest
    error.value = ''
    return
  }
  try {
    const key = props.panel.metric
    const res = await fetchSeries(props.panel.device_id, props.panel.metric, props.panel.window_minutes)
    unit.value = res.unit || ''
    const fn = mathFn.value
    const arr = res.points.map((p) => [new Date(p.ts).getTime(), applyExpr(fn, p.value)])
    seriesPoints.value = { [key]: arr }
    if (arr.length) {
      const last = res.points[res.points.length - 1]
      seriesLatest.value = { [key]: { value: applyExpr(fn, last.value), ts: last.ts } }
    } else {
      seriesLatest.value = {}
    }
    error.value = ''
  } catch (e) {
    error.value = e?.message || 'Failed to load series.'
  }
}

async function poll() {
  if (isTag.value) {
    // Fetch every tag concurrently; one dead tag must not blank the panel.
    const results = await Promise.allSettled(seriesTags.value.map((t) => fetchTagLatest(t)))
    // status_tag has no history — sample at the poll wall-clock time so the line
    // advances every poll and looks live even when the tag value is steady.
    const sampleT = Date.now()
    const nextPoints = { ...seriesPoints.value }
    const nextLatest = { ...seriesLatest.value }
    let anyOk = false
    const fn = mathFn.value
    results.forEach((res, i) => {
      const tag = seriesTags.value[i]
      if (res.status !== 'fulfilled') return
      const raw = res.value[props.panel.metric]
      if (raw == null) return
      anyOk = true
      const value = applyExpr(fn, raw)
      const arr = nextPoints[tag] || []
      nextPoints[tag] = trimWindow([...arr, [sampleT, value]])
      // Keep the tag's real update time for the "Updated …" header when present.
      nextLatest[tag] = { value, ts: res.value.ts || new Date(sampleT).toISOString() }
    })
    seriesPoints.value = nextPoints
    seriesLatest.value = nextLatest
    error.value = anyOk ? '' : 'No value reported.'
    if (anyOk) emit('updated', sampleT)
    return
  }
  if (isTable.value) {
    // Fetch every series concurrently; one dead series must not blank the panel.
    const results = await Promise.allSettled(
      seriesTags.value.map((k) =>
        fetchSchemaLatest({
          table: props.panel.table_name,
          valueCol: props.panel.metric,
          filterCol: props.panel.filter_col,
          filterVal: tableFilterVal(k),
          tsCol: props.panel.ts_col,
        }),
      ),
    )
    const sampleT = Date.now()
    const nextPoints = { ...seriesPoints.value }
    const nextLatest = { ...seriesLatest.value }
    let anyOk = false
    let newest = 0
    const fn = mathFn.value
    results.forEach((res, i) => {
      const key = seriesTags.value[i]
      if (res.status !== 'fulfilled') return
      const raw = res.value.value
      if (raw == null) return
      anyOk = true
      const value = applyExpr(fn, raw)
      // Real history tables carry a row timestamp; append only when it advances.
      // Current-state tables (no ts_col) sample at wall-clock so steady values
      // still move the line forward.
      const t = props.panel.ts_col && res.value.ts ? new Date(res.value.ts).getTime() : sampleT
      const arr = nextPoints[key] || []
      const lastT = arr.length ? arr[arr.length - 1][0] : -1
      if (t > lastT) nextPoints[key] = trimWindow([...arr, [t, value]])
      nextLatest[key] = { value, ts: res.value.ts || new Date(sampleT).toISOString() }
      if (t > newest) newest = t
    })
    seriesPoints.value = nextPoints
    seriesLatest.value = nextLatest
    error.value = anyOk ? '' : 'No value reported.'
    if (anyOk) emit('updated', newest || sampleT)
    return
  }
  try {
    const key = props.panel.metric
    const r = await fetchLatest(props.panel.device_id, props.panel.metric)
    error.value = ''
    if (r.unit) unit.value = r.unit
    if (r.value == null) {
      error.value = 'No value reported.'
      return
    }
    const t = new Date(r.ts).getTime()
    const arr = seriesPoints.value[key] || []
    const lastT = arr.length ? arr[arr.length - 1][0] : -1
    const next = { ...seriesPoints.value }
    const value = applyExpr(mathFn.value, r.value)
    if (t > lastT) next[key] = trimWindow([...arr, [t, value]])
    seriesPoints.value = next
    seriesLatest.value = { ...seriesLatest.value, [key]: { value, ts: r.ts } }
    emit('updated', t)
  } catch (e) {
    if (e?.response?.status === 404) error.value = 'No readings yet for this connection.'
    else error.value = e?.message || 'Failed to fetch latest reading.'
  }
}

function startTimer() {
  if (timer) clearInterval(timer)
  timer = setInterval(poll, pollSeconds.value * 1000)
}

// Restart the timer whenever the panel's interval changes (admin edit).
watch(pollSeconds, startTimer)

// Re-seed when the panel's data binding changes (admin edits tags/metric/window).
watch(
  () => JSON.stringify([
    props.panel.source, props.panel.device_id, props.panel.metric,
    props.panel.window_minutes, seriesTags.value,
    props.panel.table_name, props.panel.filter_col, props.panel.ts_col,
  ]),
  async () => {
    await seed()
    startTimer()
  },
)

onMounted(async () => {
  await seed()
  startTimer()
})

onBeforeUnmount(() => {
  if (timer) clearInterval(timer)
})
</script>

<template>
  <article class="panel">
    <header class="panel__head">
      <div class="panel__titlewrap">
        <h3 class="panel__title">{{ panel.title }}</h3>
      </div>
      <div class="panel__actions">
        <el-select
          :model-value="pollSeconds"
          size="small"
          class="panel__poll"
          :disabled="!canManage"
          :title="canManage ? 'Poll interval' : 'Poll interval (admin only)'"
          @update:model-value="onPollIntervalSelect"
        >
          <el-option v-for="it in POLL_INTERVALS" :key="it.value" :label="it.label" :value="it.value" />
        </el-select>
        <template v-if="canManage">
          <el-button size="small" text @click="emit('edit', panel)">Edit</el-button>
          <el-button size="small" text @click="emit('duplicate', panel)">Duplicate</el-button>
          <el-button size="small" text type="danger" @click="emit('delete', panel)">Delete</el-button>
        </template>
      </div>
    </header>

    <span class="panel__conn">
      <template v-if="isTable">
        {{ panel.table_name }}<template v-if="tableHasFilter"> · {{ tableFilters.join(', ') }}</template> · {{ panel.metric }}
      </template>
      <template v-else-if="isTag">tag · {{ seriesTags.join(', ') }} · {{ panel.metric }}</template>
      <template v-else>{{ deviceName || `device #${panel.device_id}` }} · {{ panel.metric }}</template>
    </span>

    <div class="panel__meta">
      <template v-if="showHeaderValue">
        <!-- Multi-series: coloured tag chips instead of a single big number. -->
        <template v-if="isMulti">
          <span v-for="(s, i) in seriesList" :key="s.key" class="panel__chip">
            <span class="panel__chipdot" :style="{ background: colorAt(i) }" />
            {{ s.label }}: {{ s.latest ? fmt(s.latest.value) : '—' }}{{ unit ? ' ' + unit : '' }}
          </span>
        </template>
        <template v-else>
          <span class="panel__num">{{ firstLatest ? fmt(firstLatest.value) : '—' }}</span>
          <span class="panel__unit">{{ unit }}</span>
        </template>
      </template>
    </div>

    <p v-if="error" class="panel__error">{{ error }}</p>

    <!-- Stat: big number(s) + optional sparkline (single tag only) -->
    <div v-if="vizType === 'stat'" class="panel__stat" :class="{ 'panel__stat--multi': isMulti }">
      <div v-for="(s, i) in seriesList" :key="s.key" class="panel__statrow">
        <div class="panel__statnum" :style="{ color: s.latest ? thColor(s.latest.value, colorAt(i)) : 'var(--fg)' }">
          {{ s.latest ? fmt(s.latest.value) : '—' }}<span class="panel__statunit">{{ unit }}</span>
        </div>
        <span v-if="isMulti" class="panel__statlabel" :style="{ color: colorAt(i) }">{{ s.label }}</span>
        <VChart v-if="opts.sparkline !== false && !isMulti" class="panel__spark" :option="sparklineOptionFor(s, i)" autoresize />
      </div>
    </div>

    <!-- Table: recent readings, one value column per series -->
    <div v-else-if="vizType === 'table'" class="panel__tablewrap">
      <table class="panel__table">
        <thead>
          <tr>
            <th>Time</th>
            <th v-for="(s, i) in seriesList" :key="s.key" :style="{ color: isMulti ? colorAt(i) : undefined }">
              {{ s.label }} ({{ unit }})
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(row, k) in tableRows" :key="k">
            <td>{{ row.t }}</td>
            <td v-for="(c, ci) in row.cells" :key="ci">{{ c }}</td>
          </tr>
          <tr v-if="!tableRows.length"><td :colspan="seriesList.length + 1" class="panel__tableempty">No data</td></tr>
        </tbody>
      </table>
    </div>

    <!-- Gauge: small multiples, one radial gauge per series -->
    <div v-else-if="vizType === 'gauge'" class="panel__minis" :class="{ 'panel__minis--multi': isMulti }">
      <div v-for="(s, i) in seriesList" :key="s.key" class="panel__minicell">
        <VChart class="panel__minichart" :class="{ 'panel__minichart--multi': isMulti }" :option="gaugeOptionFor(s, i)" autoresize />
        <span v-if="isMulti" class="panel__minilabel" :style="{ color: colorAt(i) }">{{ s.label }}</span>
      </div>
    </div>

    <!-- Time series / bar / histogram / bar gauge: a single multi-series chart -->
    <VChart v-else-if="isGeneric" class="panel__chart" :option="option" autoresize />
  </article>
</template>

<style scoped>
.panel {
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
  background: var(--bg-panel);
  border: 1px solid var(--border-soft);
  border-radius: var(--radius);
  padding: var(--space-4);
}

.panel__head {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: var(--space-3);
}

.panel__titlewrap {
  display: flex;
  flex-direction: column;
  gap: 2px;
  flex: 1 1 auto;
  min-width: 0;
}

.panel__conn {
  font-size: 12px;
  color: var(--fg-muted);
  overflow-wrap: anywhere;
  word-break: normal;
}

.panel__title {
  margin: 0;
  font-size: 15px;
  font-weight: 600;
  color: var(--fg);
}

.panel__actions {
  display: flex;
  align-items: center;
  gap: var(--space-1);
  flex-shrink: 0;
}

.panel__poll {
  width: 78px;
}

.panel__meta {
  display: flex;
  align-items: baseline;
  gap: var(--space-2);
  flex-wrap: wrap;
}

.panel__num {
  font-size: 24px;
  font-weight: 700;
  color: var(--fg);
  font-variant-numeric: tabular-nums;
}

.panel__unit {
  font-size: 13px;
  color: var(--fg-muted);
}

.panel__chip {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: 12px;
  color: var(--fg);
  font-variant-numeric: tabular-nums;
}

.panel__chipdot {
  width: 8px;
  height: 8px;
  border-radius: 2px;
  flex-shrink: 0;
}

.panel__error {
  color: #f5a524;
  margin: 0;
  font-size: 12px;
}

.panel__chart {
  width: 100%;
  height: 220px;
}

/* Gauge small multiples */
.panel__minis {
  display: flex;
  gap: var(--space-2);
}

.panel__minis--multi {
  flex-wrap: wrap;
}

.panel__minicell {
  flex: 1 1 0;
  min-width: 120px;
  display: flex;
  flex-direction: column;
  align-items: center;
}

.panel__minichart {
  width: 100%;
  height: 220px;
}

.panel__minichart--multi {
  height: 150px;
}

.panel__minilabel {
  font-size: 11px;
  margin-top: -10px;
  text-align: center;
  max-width: 100%;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* Stat */
.panel__stat {
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
  min-height: 120px;
}

.panel__stat--multi {
  min-height: 0;
  gap: var(--space-1);
}

.panel__statrow {
  display: flex;
  flex-direction: column;
}

.panel__statnum {
  font-size: 46px;
  font-weight: 700;
  font-variant-numeric: tabular-nums;
  line-height: 1.1;
}

.panel__stat--multi .panel__statnum {
  font-size: 26px;
}

.panel__statunit {
  font-size: 18px;
  color: var(--fg-muted);
  margin-left: 6px;
}

.panel__stat--multi .panel__statunit {
  font-size: 13px;
}

.panel__statlabel {
  font-size: 12px;
}

.panel__spark {
  width: 100%;
  height: 64px;
}

/* Table */
.panel__tablewrap {
  max-height: 240px;
  overflow-y: auto;
}

.panel__table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}

.panel__table th {
  text-align: left;
  color: var(--fg-muted);
  font-weight: 500;
  padding: 6px 8px;
  position: sticky;
  top: 0;
  background: var(--bg-panel);
  border-bottom: 1px solid var(--border-soft);
}

.panel__table td {
  padding: 5px 8px;
  color: var(--fg);
  font-variant-numeric: tabular-nums;
  border-bottom: 1px solid var(--border-soft);
}

.panel__tableempty {
  color: var(--fg-muted);
  text-align: center;
}
</style>

// scada-frontend/src/components/live/LivePanel.jsx
import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import Popover from '@mui/material/Popover'
import FormControl from '@mui/material/FormControl'
import Select from '@mui/material/Select'
import MenuItem from '@mui/material/MenuItem'
import SettingsIcon from '@mui/icons-material/Settings'
import EditIcon from '@mui/icons-material/Edit'
import ContentCopyIcon from '@mui/icons-material/ContentCopy'
import CloseIcon from '@mui/icons-material/Close'
import EChart from '@/components/charts/EChart'
import { fetchSchemaValues } from '@/api/schema'
import { colorAt } from '@/utils/seriesPalette'
import {
  usePanelSeries, buildSeriesList, computeAlertSeries, POLL_INTERVALS, TIME_RANGES,
} from './usePanelSeries'
import { usePanelPolling } from './usePanelPolling'
import {
  buildGenericOption, buildGaugeOption, buildStatSparklineOption, buildTableRows,
  thresholdColor, fmtValue,
} from './options'
import styles from './LivePanel.module.css'

/**
 * LivePanel — a single self-polling tile in the Live dashboard grid.
 *
 * Chrome + render-tree only: all data derivation lives in usePanelSeries
 * (source dispatch, cartesian expansion, math transform, units) and
 * usePanelPolling (TanStack Query wrapper: 9-field key + refreshSignal,
 * seed/poll accumulator, retry-after-4s). This component wires the two
 * together into the hydrated seriesList, then switches on vizType to render
 * stat / table / gauge small-multiples or a single generic <EChart>.
 *
 * The panel-edit dialog itself is Phase 6 (PanelEditorDialog) — the gear
 * popover's Edit/Duplicate/Delete rows just forward to the onEdit/
 * onDuplicate/onDelete callback props, same as Vue's emit('edit', panel) etc.
 */
export default function LivePanel({
  panel,
  deviceName = '',
  canManage = false,
  // Narrower than canManage: operators may change poll interval without full
  // panel-edit rights (Edit/Duplicate/Delete still gate on canManage).
  canChangePollInterval = false,
  editMode = false,
  // Bumped by the Live page's Refresh button to force an immediate re-fetch.
  refreshSignal = 0,
  onEdit,
  onDuplicate,
  onDelete,
  onPollIntervalChange,
  onUpdated,
}) {
  // Time-range selector — view-only preference, not persisted to the panel
  // record, so any viewer can widen/narrow their own window independently.
  const [rangeMinutes, setRangeMinutes] = useState(10)
  // Series-value changer — view-only override of which single filter-column
  // value a table-source panel shows. null = "use the panel's configured value".
  const [filterOverride, setFilterOverride] = useState(null)
  // All per-panel controls collapse behind a single gear button (MUI Popover,
  // not Menu, since it hosts interactive Selects that shouldn't auto-close on
  // inner clicks).
  const [gearAnchor, setGearAnchor] = useState(null)
  const gearOpen = Boolean(gearAnchor)
  const closeGear = () => setGearAnchor(null)

  const {
    vizType, opts, isTag, isTable,
    tableValueCols, effectiveFilters, tableHasFilter, showFilterChanger,
    seriesSpecs, seriesTags, mathFn, isMulti, isGeneric, showHeaderValue, unitFor,
  } = usePanelSeries(panel, { filterOverride })

  const pollSeconds = panel.poll_interval_seconds || 5

  const {
    seriesPoints, seriesLatest, unit, error,
  } = usePanelPolling({
    panel, seriesSpecs, seriesTags, isTag, isTable, mathFn, rangeMinutes, refreshSignal, onUpdated,
  })

  // Hydrated view model for every renderer below: one entry per series with
  // its colour, resolved unit and live points/latest.
  const seriesList = useMemo(
    () => buildSeriesList(seriesSpecs, { seriesPoints, seriesLatest, unitFor, deviceUnit: unit }),
    [seriesSpecs, seriesPoints, seriesLatest, unitFor, unit],
  )

  // Series currently in alert — de-duped union of every true condition's
  // referenced series, recomputed each poll via the hydrated seriesList.
  const alertSeries = useMemo(() => computeAlertSeries(panel, seriesList), [panel.options, seriesList])

  // Single-value header (first/only series).
  const firstLatest = seriesLatest[seriesSpecs[0]?.key] || null
  const headerUnit = seriesList[0]?.unit || ''

  // One shared ECharts option object for the 9 "generic" viz types — pure
  // function, no hooks, memoized so <EChart notMerge> doesn't diff a fresh
  // object identity on every render that didn't actually change the data.
  const option = useMemo(
    () => (isGeneric ? buildGenericOption(vizType, seriesList, opts) : null),
    [isGeneric, vizType, seriesList, opts],
  )

  // statetimeline/heatmap grow with series count; every other generic viz
  // gets a fixed height (the panel__chart CSS class's flex-grow still lets
  // it fill remaining tile space beyond this).
  const chartHeight = useMemo(() => {
    if (vizType === 'statetimeline') return `${Math.max(120, seriesList.length * 44 + 40)}px`
    if (vizType === 'heatmap') return `${Math.max(160, seriesList.length * 34 + 60)}px`
    return '220px'
  }, [vizType, seriesList.length])

  const tableRows = useMemo(() => buildTableRows(seriesList, opts), [seriesList, opts])

  // Available values for the series-value changer — fetched once (view-only,
  // not polled), mirroring Vue's onMounted-only fetchSchemaValues call.
  const filtersQuery = useQuery({
    queryKey: ['live-panel-filter-values', panel.table_name, panel.filter_col, panel.datasource_id],
    queryFn: () => fetchSchemaValues(panel.table_name, panel.filter_col, 500, panel.datasource_id || undefined),
    enabled: showFilterChanger,
  })
  const availableFilters = filtersQuery.data || []

  return (
    <article className={styles.panel}>
      <header className={styles.panel__head}>
        <div className={styles.panel__titlewrap}>
          {editMode && canManage && (
            <button
              type="button"
              // "panel__drag" (unhashed, global) is load-bearing: react-grid-layout's
              // draggableHandle=".panel__drag" (LivePage.jsx) matches it via DOM
              // selector at runtime, which a CSS-Modules-hashed class name can't
              // satisfy. styles.panel__drag still supplies the visual styling.
              className={`${styles.panel__drag} panel__drag`}
              title="Drag to move"
              aria-label="Drag to move panel"
            >
              ⠿
            </button>
          )}
          <h3 className={styles.panel__title}>{panel.title}</h3>
        </div>

        <div className={styles.panel__actions}>
          <button
            type="button"
            className={`${styles.panel__gear} ${gearOpen ? styles['panel__gear--active'] : ''}`}
            title="Panel settings"
            aria-label="Panel settings"
            onClick={(e) => setGearAnchor(e.currentTarget)}
          >
            <SettingsIcon fontSize="small" />
          </button>

          <Popover
            open={gearOpen}
            anchorEl={gearAnchor}
            onClose={closeGear}
            anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
            transformOrigin={{ vertical: 'top', horizontal: 'right' }}
            slotProps={{ paper: { className: styles.gearpopPaper } }}
          >
            <div className={styles.gearpop}>
              {showFilterChanger && (
                <div className={styles.gearpop__row}>
                  <span className={styles.gearpop__label}>Series value</span>
                  <FormControl size="small" className={styles.gearpop__control}>
                    <Select
                      value={effectiveFilters[0] ?? ''}
                      onChange={(e) => setFilterOverride(e.target.value)}
                    >
                      {availableFilters.map((v) => (
                        <MenuItem key={v} value={v}>{v}</MenuItem>
                      ))}
                    </Select>
                  </FormControl>
                </div>
              )}

              <div className={styles.gearpop__row}>
                <span className={styles.gearpop__label}>Time range</span>
                <FormControl size="small" className={styles.gearpop__control}>
                  <Select
                    value={rangeMinutes}
                    onChange={(e) => setRangeMinutes(Number(e.target.value))}
                  >
                    {TIME_RANGES.map((it) => (
                      <MenuItem key={it.value} value={it.value}>{it.label}</MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </div>

              <div className={styles.gearpop__row}>
                <span className={styles.gearpop__label}>Poll interval</span>
                <FormControl size="small" className={styles.gearpop__control} disabled={!canChangePollInterval}>
                  <Select
                    value={pollSeconds}
                    disabled={!canChangePollInterval}
                    title={canChangePollInterval ? '' : 'Operator or admin only'}
                    onChange={(e) => onPollIntervalChange?.(panel, Number(e.target.value))}
                  >
                    {POLL_INTERVALS.map((it) => (
                      <MenuItem key={it.value} value={it.value}>{it.label}</MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </div>

              {canManage && (
                <>
                  <div className={styles.gearpop__divider} />
                  <button
                    type="button"
                    className={styles.gearpop__action}
                    onClick={() => { closeGear(); onEdit?.(panel) }}
                  >
                    <EditIcon fontSize="inherit" /> Edit panel
                  </button>
                  <button
                    type="button"
                    className={styles.gearpop__action}
                    onClick={() => { closeGear(); onDuplicate?.(panel) }}
                  >
                    <ContentCopyIcon fontSize="inherit" /> Duplicate
                  </button>
                  <button
                    type="button"
                    className={`${styles.gearpop__action} ${styles['gearpop__action--danger']}`}
                    onClick={() => { closeGear(); onDelete?.(panel) }}
                  >
                    <CloseIcon fontSize="inherit" /> Delete
                  </button>
                </>
              )}
            </div>
          </Popover>
        </div>
      </header>

      <span className={styles.panel__conn}>
        {isTable && (
          <>
            {panel.table_name}
            {tableHasFilter && ` · ${effectiveFilters.join(', ')}`}
            {` · ${tableValueCols.join(', ')}`}
          </>
        )}
        {!isTable && isTag && `tag · ${seriesTags.join(', ')} · ${panel.metric}`}
        {!isTable && !isTag && `${deviceName || `device #${panel.device_id}`} · ${panel.metric}`}
      </span>

      <div className={styles.panel__meta}>
        {showHeaderValue && (
          isMulti ? (
            seriesList.map((s, i) => (
              <span key={s.key} className={styles.panel__chip}>
                <span className={styles.panel__chipdot} style={{ background: colorAt(i) }} />
                {s.label}: {s.latest ? fmtValue(s.latest.value, opts.decimals) : '—'}{s.unit ? ` ${s.unit}` : ''}
              </span>
            ))
          ) : (
            <>
              <span className={styles.panel__num}>{firstLatest ? fmtValue(firstLatest.value, opts.decimals) : '—'}</span>
              <span className={styles.panel__unit}>{headerUnit}</span>
            </>
          )
        )}
      </div>

      {error && <p className={styles.panel__error}>{error}</p>}

      {alertSeries.length > 0 && (
        <div className={styles.panel__alert} role="status">
          {alertSeries.join(', ')} ALERTS
        </div>
      )}

      {vizType === 'stat' && (
        <div className={`${styles.panel__stat} ${isMulti ? styles['panel__stat--multi'] : ''}`}>
          {seriesList.map((s, i) => (
            <div key={s.key} className={styles.panel__statrow}>
              <div
                className={styles.panel__statnum}
                style={{ color: s.latest ? thresholdColor(s.latest.value, colorAt(i), opts.warn, opts.crit) : 'var(--fg)' }}
              >
                {s.latest ? fmtValue(s.latest.value, opts.decimals) : '—'}
                <span className={styles.panel__statunit}>{s.unit}</span>
              </div>
              {isMulti && (
                <span className={styles.panel__statlabel} style={{ color: colorAt(i) }}>{s.label}</span>
              )}
              {opts.sparkline !== false && !isMulti && (
                <EChart
                  key={`stat-${s.key}`}
                  className={styles.panel__spark}
                  height="64px"
                  option={buildStatSparklineOption(s, i)}
                />
              )}
            </div>
          ))}
        </div>
      )}

      {vizType === 'table' && (
        <div className={styles.panel__tablewrap}>
          <table className={styles.panel__table}>
            <thead>
              <tr>
                <th>Time</th>
                {seriesList.map((s, i) => (
                  <th key={s.key} style={{ color: isMulti ? colorAt(i) : undefined }}>
                    {s.label}{s.unit ? ` (${s.unit})` : ''}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {tableRows.map((row, k) => (
                // eslint-disable-next-line react/no-array-index-key
                <tr key={k}>
                  <td>{row.t}</td>
                  {row.cells.map((c, ci) => (
                    // eslint-disable-next-line react/no-array-index-key
                    <td key={ci}>{c}</td>
                  ))}
                </tr>
              ))}
              {!tableRows.length && (
                <tr>
                  <td colSpan={seriesList.length + 1} className={styles.panel__tableempty}>No data</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      )}

      {vizType === 'gauge' && (
        <div className={`${styles.panel__minis} ${isMulti ? styles['panel__minis--multi'] : ''}`}>
          {seriesList.map((s, i) => (
            <div key={s.key} className={styles.panel__minicell}>
              <EChart
                key={`gauge-${s.key}`}
                className={`${styles.panel__minichart} ${isMulti ? styles['panel__minichart--multi'] : ''}`}
                option={buildGaugeOption(s, i, opts, isMulti)}
              />
              {isMulti && (
                <span className={styles.panel__minilabel} style={{ color: colorAt(i) }}>{s.label}</span>
              )}
            </div>
          ))}
        </div>
      )}

      {isGeneric && (
        <EChart
          key={vizType}
          className={styles.panel__chart}
          height={chartHeight}
          option={option}
        />
      )}
    </article>
  )
}
