// scada-frontend/src/components/AppSidebar.vue
<script setup>
/**
 * AppSidebar — collapsible left navigation menu rendered inside AppShell.
 * Navigation items are role-aware: the Accounts link is only shown to admin users.
 * Props: collapsed (Boolean) — when true, hides text labels and the brand title.
 */
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { useAuthStore } from '@/stores/auth'

defineProps({
  collapsed: { type: Boolean, default: false },
})

const route = useRoute()
const auth = useAuthStore()
const activeIndex = computed(() => '/' + (route.path.split('/')[1] || ''))

const items = computed(() => {
  const base = [
    { path: '/', title: 'Overview', icon: 'Odometer' },
    { path: '/devices', title: 'Devices', icon: 'Cpu' },
    { path: '/alarms', title: 'Alarms', icon: 'WarningFilled' },
    { path: '/trends', title: 'Trends', icon: 'TrendCharts' },
    { path: '/live', title: 'Live', icon: 'VideoPlay' },
    { path: '/events', title: 'Events', icon: 'List' },
    { path: '/settings', title: 'Settings', icon: 'Setting' },
  ]
  if (auth.role === 'admin') {
    base.push({ path: '/accounts', title: 'Accounts', icon: 'User' })
  }
  return base
})
</script>

<template>
  <div class="sidebar">
    <div class="sidebar__brand">
      <span class="sidebar__logo" aria-hidden="true">⚙</span>
      <span v-show="!collapsed" class="sidebar__title">MML Portal</span>
    </div>
    <el-menu
      class="sidebar__menu"
      :default-active="activeIndex"
      :collapse="collapsed"
      router
      background-color="transparent"
      text-color="var(--fg-muted)"
      active-text-color="var(--accent)"
    >
      <el-menu-item v-for="item in items" :key="item.path" :index="item.path" :route="item.path">
        <el-icon><component :is="item.icon" /></el-icon>
        <template #title>{{ item.title }}</template>
      </el-menu-item>
    </el-menu>
  </div>
</template>

<style scoped>
.sidebar {
  display: flex;
  flex-direction: column;
  height: 100%;
}

.sidebar__brand {
  height: var(--header-h);
  display: flex;
  align-items: center;
  gap: var(--space-3);
  padding: 0 var(--space-5);
  border-bottom: 1px solid var(--border-soft);
  color: var(--fg);
  font-weight: 600;
  letter-spacing: 0.04em;
}

.sidebar__logo {
  font-size: 20px;
  color: var(--accent);
}

.sidebar__title {
  font-size: 14px;
}

.sidebar__menu {
  border-right: none;
  flex: 1;
  padding-top: var(--space-2);
}

.sidebar__menu :deep(.el-menu-item) {
  height: 44px;
  line-height: 44px;
  margin: 2px var(--space-2);
  border-radius: var(--radius-sm);
}

.sidebar__menu :deep(.el-menu-item.is-active) {
  background: var(--accent-soft);
}

.sidebar__menu :deep(.el-menu-item:hover) {
  background: rgba(255, 255, 255, 0.04);
}
</style>

// scada-frontend/src/components/AppSidebar/AppSidebar.jsx
import { useLocation, useNavigate } from 'react-router-dom'
import List from '@mui/material/List'
import ListItemButton from '@mui/material/ListItemButton'
import ListItemIcon from '@mui/material/ListItemIcon'
import ListItemText from '@mui/material/ListItemText'
import SpeedOutlined from '@mui/icons-material/SpeedOutlined'
import MemoryOutlined from '@mui/icons-material/MemoryOutlined'
import WarningRounded from '@mui/icons-material/WarningRounded'
import PlayCircleOutlined from '@mui/icons-material/PlayCircleOutlined'
import ListAltOutlined from '@mui/icons-material/ListAltOutlined'
import SettingsOutlined from '@mui/icons-material/SettingsOutlined'
import PersonOutlined from '@mui/icons-material/PersonOutlined'
import { useAuthStore } from '@/stores/auth'
import styles from './AppSidebar.module.css'

// Nav items ported 1:1 from AppSidebar.vue's `items` computed (Trends
// removed — Grafana/trends are gone from this branch). Accounts is
// appended only for admin users, same as the Vue version.
const BASE_ITEMS = [
  { path: '/', title: 'Overview', Icon: SpeedOutlined },
  { path: '/live', title: 'Live', Icon: PlayCircleOutlined },
  { path: '/events', title: 'Events', Icon: ListAltOutlined },
  { path: '/alarms', title: 'Alarms', Icon: WarningRounded },
  { path: '/devices', title: 'Devices', Icon: MemoryOutlined },
  { path: '/settings', title: 'Settings', Icon: SettingsOutlined },
]

/**
 * AppSidebar — collapsible left navigation menu rendered inside AppShell.
 * Navigation items are role-aware: the Accounts link is only shown to admin
 * users. Props: collapsed (Boolean) — when true, hides text labels and the
 * brand title.
 */
export default function AppSidebar({ collapsed }) {
  const location = useLocation()
  const navigate = useNavigate()
  const role = useAuthStore((s) => s.user?.role ?? null)

  const activeIndex = '/' + (location.pathname.split('/')[1] || '')

  const items =
    role === 'admin'
      ? [...BASE_ITEMS, { path: '/accounts', title: 'Accounts', Icon: PersonOutlined }]
      : BASE_ITEMS

  return (
    <div className={styles.sidebar}>
      <div className={styles.brand}>
        <span className={styles.logo} aria-hidden="true">
          ⚙
        </span>
        {!collapsed && <span className={styles.title}>MML Portal</span>}
      </div>
      <List className={styles.menu} disablePadding>
        {items.map((item) => {
          const active = activeIndex === item.path
          return (
            <ListItemButton
              key={item.path}
              className={`${styles.menuItem} ${active ? styles.menuItemActive : ''}`}
              selected={active}
              onClick={() => navigate(item.path)}
            >
              <ListItemIcon className={styles.menuIcon}>
                <item.Icon fontSize="small" />
              </ListItemIcon>
              {!collapsed && <ListItemText primary={item.title} />}
            </ListItemButton>
          )
        })}
      </List>
    </div>
  )
}
