// scada-frontend/src/pages/AccountsPage.vue
<script setup>
/**
 * AccountsPage — admin-only user management page (route: /accounts).
 * Lists all users in a table and provides Create / Edit / Delete actions via
 * dialogs backed by useUsersStore. Accessible only to users with role 'admin'
 * (enforced by requiresRole in the router).
 */
import { onMounted, reactive, ref } from 'vue'
import { storeToRefs } from 'pinia'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useUsersStore } from '@/stores/users'

const store = useUsersStore()
const { list, loading } = storeToRefs(store)

const dialogVisible = ref(false)
const dialogMode = ref('create') // 'create' | 'edit'
const submitting = ref(false)
const editingId = ref(null)

const blankForm = () => ({
  username: '',
  password: '',
  role: 'operator',
  display_name: '',
  email: '',
})
const form = reactive(blankForm())

function resetForm() {
  Object.assign(form, blankForm())
}

function openCreate() {
  dialogMode.value = 'create'
  editingId.value = null
  resetForm()
  dialogVisible.value = true
}

function openEdit(row) {
  dialogMode.value = 'edit'
  editingId.value = row.id
  resetForm()
  form.username = row.username
  form.role = row.role
  form.display_name = row.display_name
  form.email = row.email || ''
  dialogVisible.value = true
}

async function submit() {
  if (!form.display_name.trim()) {
    ElMessage.warning('Display name is required')
    return
  }
  if (dialogMode.value === 'create' && !form.username.trim()) {
    ElMessage.warning('Username is required')
    return
  }
  submitting.value = true
  try {
    if (dialogMode.value === 'create') {
      await store.create({
        username: form.username.trim(),
        password: form.password,
        role: form.role,
        display_name: form.display_name.trim(),
        email: form.email.trim() || null,
      })
      ElMessage.success('User created')
    } else {
      await store.update(editingId.value, {
        role: form.role,
        display_name: form.display_name.trim(),
        email: form.email.trim() || null,
      })
      ElMessage.success('User updated')
    }
    dialogVisible.value = false
  } catch (e) {
    ElMessage.error(e?.response?.data?.detail || 'Save failed')
  } finally {
    submitting.value = false
  }
}

async function confirmDelete(row) {
  try {
    await ElMessageBox.confirm(
      `Delete user "${row.username}"? This cannot be undone.`,
      'Delete user',
      { type: 'warning', confirmButtonText: 'Delete', cancelButtonText: 'Cancel' },
    )
  } catch {
    return // cancelled
  }
  try {
    await store.remove(row.id)
    ElMessage.success('User deleted')
  } catch (e) {
    ElMessage.error(e?.response?.data?.detail || 'Delete failed')
  }
}

function formatDate(value) {
  if (!value) return '—'
  return new Date(value).toLocaleString()
}

onMounted(() => store.load())
</script>

<template>
  <div class="page">
    <header class="page__head">
      <h2 class="page__title">Accounts</h2>
      <div class="page__actions">
        <el-button :icon="'Refresh'" @click="store.load()" :loading="loading">
          Refresh
        </el-button>
        <el-button type="primary" :icon="'Plus'" @click="openCreate">
          Add user
        </el-button>
      </div>
    </header>

    <el-alert
      v-if="store.error"
      :title="store.error"
      type="error"
      show-icon
      :closable="false"
    />

    <el-table :data="list" v-loading="loading" stripe size="default" style="width: 100%">
      <el-table-column prop="id" label="ID" width="80" />
      <el-table-column prop="username" label="Username" min-width="140" />
      <el-table-column prop="display_name" label="Display name" min-width="160" />
      <el-table-column label="Role" width="120">
        <template #default="{ row }">
          <el-tag :type="row.role === 'admin' ? 'danger' : 'info'" disable-transitions>
            {{ row.role }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="email" label="Email" min-width="200">
        <template #default="{ row }">{{ row.email || '—' }}</template>
      </el-table-column>
      <el-table-column label="Created" min-width="180">
        <template #default="{ row }">{{ formatDate(row.created_at) }}</template>
      </el-table-column>
      <el-table-column label="Actions" width="160" fixed="right">
        <template #default="{ row }">
          <el-button size="small" :icon="'Edit'" @click="openEdit(row)" />
          <el-button
            size="small"
            type="danger"
            :icon="'Delete'"
            @click="confirmDelete(row)"
          />
        </template>
      </el-table-column>
    </el-table>

    <el-dialog
      v-model="dialogVisible"
      :title="dialogMode === 'create' ? 'Add user' : 'Edit user'"
      width="440px"
    >
      <el-form label-position="top">
        <el-form-item label="Username">
          <el-input
            v-model="form.username"
            :disabled="dialogMode === 'edit'"
            placeholder="Login username"
          />
        </el-form-item>
        <el-form-item v-if="dialogMode === 'create'" label="Password">
          <el-input
            v-model="form.password"
            type="password"
            show-password
            placeholder="At least 8 characters"
          />
        </el-form-item>
        <el-form-item label="Display name">
          <el-input v-model="form.display_name" placeholder="Full name" />
        </el-form-item>
        <el-form-item label="Role">
          <el-select v-model="form.role" style="width: 100%">
            <el-option label="operator" value="operator" />
            <el-option label="admin" value="admin" />
          </el-select>
        </el-form-item>
        <el-form-item label="Email (optional)">
          <el-input v-model="form.email" placeholder="name@example.com" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">Cancel</el-button>
        <el-button type="primary" :loading="submitting" @click="submit">
          {{ dialogMode === 'create' ? 'Create' : 'Save' }}
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<style scoped>
.page {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
}

.page__head {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.page__actions {
  display: flex;
  gap: var(--space-2);
}

.page__title {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
}
</style>

// scada-frontend/src/pages/AccountsPage.jsx
import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Controller, useForm } from 'react-hook-form'
import Table from '@mui/material/Table'
import TableBody from '@mui/material/TableBody'
import TableCell from '@mui/material/TableCell'
import TableContainer from '@mui/material/TableContainer'
import TableHead from '@mui/material/TableHead'
import TableRow from '@mui/material/TableRow'
import Paper from '@mui/material/Paper'
import Chip from '@mui/material/Chip'
import Button from '@mui/material/Button'
import IconButton from '@mui/material/IconButton'
import TextField from '@mui/material/TextField'
import Select from '@mui/material/Select'
import MenuItem from '@mui/material/MenuItem'
import InputLabel from '@mui/material/InputLabel'
import FormControl from '@mui/material/FormControl'
import Dialog from '@mui/material/Dialog'
import DialogTitle from '@mui/material/DialogTitle'
import DialogContent from '@mui/material/DialogContent'
import DialogActions from '@mui/material/DialogActions'
import Alert from '@mui/material/Alert'
import Snackbar from '@mui/material/Snackbar'
import RefreshIcon from '@mui/icons-material/Refresh'
import AddIcon from '@mui/icons-material/Add'
import EditIcon from '@mui/icons-material/Edit'
import DeleteIcon from '@mui/icons-material/Delete'
import { fetchUsers, createUser, updateUser, deleteUser } from '@/api/users'
import styles from './AccountsPage.module.css'

/**
 * AccountsPage — admin-only user management page (route: /accounts).
 * Lists all users in a table and provides Create / Edit / Delete actions via
 * dialogs. Role gating (admin-only) is enforced upstream by
 * handle.requiresRole in router/routes.jsx + RequireAuth — this page assumes
 * it is only ever rendered for an admin. Ported from AccountsPage.vue
 * (Pinia useUsersStore) onto TanStack Query (list + mutations).
 */

const BLANK_FORM = { username: '', password: '', role: 'operator', display_name: '', email: '' }

function formatDate(value) {
  if (!value) return '—'
  return new Date(value).toLocaleString()
}

export default function AccountsPage() {
  const queryClient = useQueryClient()
  const {
    data: list = [],
    isFetching,
    error: listError,
    refetch,
  } = useQuery({ queryKey: ['users'], queryFn: fetchUsers })

  const [dialogOpen, setDialogOpen] = useState(false)
  const [dialogMode, setDialogMode] = useState('create') // 'create' | 'edit'
  const [editingId, setEditingId] = useState(null)
  const [dialogError, setDialogError] = useState('')

  const [deleteTarget, setDeleteTarget] = useState(null)
  const [deleteError, setDeleteError] = useState('')

  const [snackbar, setSnackbar] = useState({ open: false, message: '', severity: 'success' })
  function notify(message, severity = 'success') {
    setSnackbar({ open: true, message, severity })
  }

  const {
    register,
    handleSubmit,
    reset,
    control,
    formState: { errors },
  } = useForm({ defaultValues: BLANK_FORM })

  const invalidateUsers = () => queryClient.invalidateQueries({ queryKey: ['users'] })

  const createMutation = useMutation({
    mutationFn: createUser,
    onSuccess: () => {
      invalidateUsers()
      notify('User created')
      setDialogOpen(false)
    },
    onError: (e) => setDialogError(e?.response?.data?.detail || 'Save failed'),
  })

  const updateMutation = useMutation({
    mutationFn: ({ id, payload }) => updateUser(id, payload),
    onSuccess: () => {
      invalidateUsers()
      notify('User updated')
      setDialogOpen(false)
    },
    onError: (e) => setDialogError(e?.response?.data?.detail || 'Save failed'),
  })

  const deleteMutation = useMutation({
    mutationFn: deleteUser,
    onSuccess: () => {
      invalidateUsers()
      notify('User deleted')
      setDeleteTarget(null)
    },
    onError: (e) => setDeleteError(e?.response?.data?.detail || 'Delete failed'),
  })

  const submitting = createMutation.isPending || updateMutation.isPending

  function openCreate() {
    setDialogMode('create')
    setEditingId(null)
    setDialogError('')
    reset(BLANK_FORM)
    setDialogOpen(true)
  }

  function openEdit(row) {
    setDialogMode('edit')
    setEditingId(row.id)
    setDialogError('')
    reset({
      username: row.username,
      password: '',
      role: row.role,
      display_name: row.display_name,
      email: row.email || '',
    })
    setDialogOpen(true)
  }

  function onSubmit(values) {
    setDialogError('')
    if (dialogMode === 'create') {
      createMutation.mutate({
        username: values.username.trim(),
        password: values.password,
        role: values.role,
        display_name: values.display_name.trim(),
        email: values.email.trim() || null,
      })
    } else {
      updateMutation.mutate({
        id: editingId,
        payload: {
          role: values.role,
          display_name: values.display_name.trim(),
          email: values.email.trim() || null,
        },
      })
    }
  }

  function confirmDelete(row) {
    setDeleteError('')
    setDeleteTarget(row)
  }

  function handleDelete() {
    if (deleteTarget) deleteMutation.mutate(deleteTarget.id)
  }

  return (
    <div className={styles.page}>
      <header className={styles.head}>
        <h2 className={styles.title}>Accounts</h2>
        <div className={styles.actions}>
          <Button startIcon={<RefreshIcon />} onClick={() => refetch()} loading={isFetching}>
            Refresh
          </Button>
          <Button variant="contained" startIcon={<AddIcon />} onClick={openCreate}>
            Add user
          </Button>
        </div>
      </header>

      {listError && (
        <Alert severity="error">
          {listError?.response?.data?.detail || listError?.message || 'Failed to load users'}
        </Alert>
      )}

      <TableContainer component={Paper} variant="outlined">
        <Table size="medium">
          <TableHead>
            <TableRow>
              <TableCell width={80}>ID</TableCell>
              <TableCell>Username</TableCell>
              <TableCell>Display name</TableCell>
              <TableCell width={120}>Role</TableCell>
              <TableCell>Email</TableCell>
              <TableCell>Created</TableCell>
              <TableCell width={120} align="right">
                Actions
              </TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {list.map((row) => (
              <TableRow key={row.id} hover>
                <TableCell>{row.id}</TableCell>
                <TableCell>{row.username}</TableCell>
                <TableCell>{row.display_name}</TableCell>
                <TableCell>
                  <Chip
                    label={row.role}
                    color={row.role === 'admin' ? 'error' : 'default'}
                    size="small"
                  />
                </TableCell>
                <TableCell>{row.email || '—'}</TableCell>
                <TableCell>{formatDate(row.created_at)}</TableCell>
                <TableCell align="right">
                  <IconButton size="small" aria-label="Edit user" onClick={() => openEdit(row)}>
                    <EditIcon fontSize="small" />
                  </IconButton>
                  <IconButton
                    size="small"
                    color="error"
                    aria-label="Delete user"
                    onClick={() => confirmDelete(row)}
                  >
                    <DeleteIcon fontSize="small" />
                  </IconButton>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>

      {/* Create / edit dialog */}
      <Dialog open={dialogOpen} onClose={() => setDialogOpen(false)} fullWidth maxWidth="xs">
        <DialogTitle>{dialogMode === 'create' ? 'Add user' : 'Edit user'}</DialogTitle>
        <form onSubmit={handleSubmit(onSubmit)}>
          <DialogContent sx={{ display: 'flex', flexDirection: 'column', gap: 2, pt: '8px !important' }}>
            <TextField
              label="Username"
              placeholder="Login username"
              disabled={dialogMode === 'edit'}
              fullWidth
              error={!!errors.username}
              helperText={errors.username ? 'Username is required' : ' '}
              {...register('username', { required: dialogMode === 'create' })}
            />
            {dialogMode === 'create' && (
              <TextField
                label="Password"
                type="password"
                placeholder="At least 8 characters"
                fullWidth
                {...register('password')}
              />
            )}
            <TextField
              label="Display name"
              placeholder="Full name"
              fullWidth
              error={!!errors.display_name}
              helperText={errors.display_name ? 'Display name is required' : ' '}
              {...register('display_name', { required: true })}
            />
            <FormControl fullWidth>
              <InputLabel id="accounts-role-label">Role</InputLabel>
              <Controller
                name="role"
                control={control}
                render={({ field }) => (
                  <Select labelId="accounts-role-label" label="Role" {...field}>
                    <MenuItem value="operator">operator</MenuItem>
                    <MenuItem value="admin">admin</MenuItem>
                  </Select>
                )}
              />
            </FormControl>
            <TextField
              label="Email (optional)"
              placeholder="name@example.com"
              fullWidth
              {...register('email')}
            />
            {dialogError && <Alert severity="error">{dialogError}</Alert>}
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setDialogOpen(false)}>Cancel</Button>
            <Button type="submit" variant="contained" loading={submitting}>
              {dialogMode === 'create' ? 'Create' : 'Save'}
            </Button>
          </DialogActions>
        </form>
      </Dialog>

      {/* Delete confirmation */}
      <Dialog open={!!deleteTarget} onClose={() => setDeleteTarget(null)} fullWidth maxWidth="xs">
        <DialogTitle>Delete user</DialogTitle>
        <DialogContent sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
          <p className={styles.confirmText}>
            Delete user "{deleteTarget?.username}"? This cannot be undone.
          </p>
          {deleteError && <Alert severity="error">{deleteError}</Alert>}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setDeleteTarget(null)}>Cancel</Button>
          <Button
            color="error"
            variant="contained"
            loading={deleteMutation.isPending}
            onClick={handleDelete}
          >
            Delete
          </Button>
        </DialogActions>
      </Dialog>

      <Snackbar
        open={snackbar.open}
        autoHideDuration={4000}
        onClose={() => setSnackbar((s) => ({ ...s, open: false }))}
        anchorOrigin={{ vertical: 'top', horizontal: 'center' }}
      >
        <Alert
          severity={snackbar.severity}
          onClose={() => setSnackbar((s) => ({ ...s, open: false }))}
          sx={{ width: '100%' }}
        >
          {snackbar.message}
        </Alert>
      </Snackbar>
    </div>
  )
}
