// scada-frontend/src/pages/DevicesPage.jsx
import { useQuery } from '@tanstack/react-query'
import Table from '@mui/material/Table'
import TableBody from '@mui/material/TableBody'
import TableCell from '@mui/material/TableCell'
import TableContainer from '@mui/material/TableContainer'
import TableHead from '@mui/material/TableHead'
import TableRow from '@mui/material/TableRow'
import Paper from '@mui/material/Paper'
import Chip from '@mui/material/Chip'
import LinearProgress from '@mui/material/LinearProgress'
import Button from '@mui/material/Button'
import RefreshIcon from '@mui/icons-material/Refresh'
import { fetchDevices } from '@/api/devices'
import styles from './DevicesPage.module.css'

/**
 * DevicesPage — device inventory table (route: /devices).
 * Fetches the device list via TanStack Query on mount and displays ID,
 * name, location, status (online/degraded/offline), CPU progress bar, and
 * uptime. Refresh button re-fetches from the backend. Ported from
 * DevicesPage.vue, which drove the same list off useDevicesStore (Pinia).
 */

const CHIP_COLOR = {
  online: 'success',
  degraded: 'warning',
  offline: 'error',
}

export default function DevicesPage() {
  const { data: list = [], isFetching, refetch } = useQuery({
    queryKey: ['devices'],
    queryFn: fetchDevices,
  })

  return (
    <div className={styles.page}>
      <header className={styles.head}>
        <h2 className={styles.title}>Devices</h2>
        <Button
          variant="contained"
          startIcon={<RefreshIcon />}
          onClick={() => refetch()}
          loading={isFetching}
        >
          Refresh
        </Button>
      </header>

      <TableContainer component={Paper} variant="outlined">
        <Table size="medium">
          <TableHead>
            <TableRow>
              <TableCell width={120}>ID</TableCell>
              <TableCell>Name</TableCell>
              <TableCell>Location</TableCell>
              <TableCell width={130}>Status</TableCell>
              <TableCell width={180}>CPU</TableCell>
              <TableCell width={120}>Uptime</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {list.map((row) => (
              <TableRow key={row.id} hover>
                <TableCell>{row.id}</TableCell>
                <TableCell>{row.name}</TableCell>
                <TableCell>{row.location}</TableCell>
                <TableCell>
                  <Chip
                    label={row.status}
                    color={CHIP_COLOR[row.status] || 'default'}
                    size="small"
                  />
                </TableCell>
                <TableCell>
                  <div className={styles.cpuCell}>
                    <LinearProgress
                      className={styles.cpuBar}
                      variant="determinate"
                      value={row.cpu}
                    />
                    <span className={styles.cpuText}>{row.cpu}%</span>
                  </div>
                </TableCell>
                <TableCell>{row.uptime}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
    </div>
  )
}

// scada-frontend/src/pages/DevicesPage.vue
<script setup>
/**
 * DevicesPage — device inventory table (route: /devices).
 * Fetches the device list from useDevicesStore on mount and displays
 * ID, name, location, status (online/degraded/offline), CPU progress bar,
 * and uptime. Refresh button re-fetches from the backend.
 */
import { onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useDevicesStore } from '@/stores/devices'

const store = useDevicesStore()
const { list, loading } = storeToRefs(store)

onMounted(() => store.load())

const tagType = (s) =>
  s === 'online' ? 'success' : s === 'degraded' ? 'warning' : 'danger'
</script>

<template>
  <div class="page">
    <header class="page__head">
      <h2 class="page__title">Devices</h2>
      <el-button type="primary" :icon="'Refresh'" @click="store.load()" :loading="loading">
        Refresh
      </el-button>
    </header>

    <el-table :data="list" v-loading="loading" stripe size="default" style="width: 100%">
      <el-table-column prop="id" label="ID" width="120" />
      <el-table-column prop="name" label="Name" min-width="180" />
      <el-table-column prop="location" label="Location" min-width="200" />
      <el-table-column label="Status" width="130">
        <template #default="{ row }">
          <el-tag :type="tagType(row.status)" disable-transitions>
            {{ row.status }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="CPU" width="160">
        <template #default="{ row }">
          <el-progress :percentage="row.cpu" :stroke-width="8" :show-text="false" />
          <span class="cpu-text">{{ row.cpu }}%</span>
        </template>
      </el-table-column>
      <el-table-column prop="uptime" label="Uptime" width="120" />
    </el-table>
  </div>
</template>

<style scoped>
.page {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
}

.page__head {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.page__title {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
}

.cpu-text {
  display: inline-block;
  margin-left: var(--space-2);
  color: var(--fg-muted);
  font-variant-numeric: tabular-nums;
  font-size: 12px;
}
</style>
