// scada-frontend/src/pages/NotFoundPage.jsx
import Button from '@mui/material/Button'
import { useNavigate } from 'react-router-dom'
import styles from './NotFoundPage.module.css'

/**
 * NotFoundPage — 404 fallback rendered for any unmatched route.
 * Shows a large "404" heading and a button that navigates back to the overview.
 */
export default function NotFoundPage() {
  const navigate = useNavigate()

  return (
    <div className={styles.nf}>
      <h1 className={styles.code}>404</h1>
      <p className={styles.msg}>That route doesn't exist.</p>
      <Button variant="contained" onClick={() => navigate('/', { replace: true })}>
        Back to overview
      </Button>
    </div>
  )
}

// scada-frontend/src/pages/NotFoundPage.vue
<script setup>
// NotFoundPage — 404 fallback rendered for any unmatched route.
// Shows a large "404" heading and a button that navigates back to the overview.
import { useRouter } from 'vue-router'
const router = useRouter()
</script>

<template>
  <div class="nf">
    <h1 class="nf__code">404</h1>
    <p class="nf__msg">That route doesn't exist.</p>
    <el-button type="primary" @click="router.replace('/')">Back to overview</el-button>
  </div>
</template>

<style scoped>
.nf {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: var(--space-4);
  height: 100vh;
  background: var(--bg-app);
  color: var(--fg);
}
.nf__code {
  font-size: 64px;
  margin: 0;
  color: var(--fg-muted);
}
.nf__msg {
  color: var(--fg-muted);
}
</style>
