// scada-frontend/src/pages/SettingsPage.vue
<script setup>
/**
 * SettingsPage — the control-console for portal-wide parameters (route: /settings).
 * Laid out as rack modules: APPEARANCE (color faceplate), ACQUISITION (poll
 * cadence + alerts), and DATA SOURCES (admin-managed saved DB connections).
 *
 * Theme + acquisition prefs persist to localStorage via the settings store
 * (theme applies live; acquisition needs Save). Connections live server-side
 * (api/datasources) so Live panels can bind to them; each saves on its own and
 * can be tested against a real database.
 */
import { computed, onMounted, reactive, ref } from 'vue'
import { storeToRefs } from 'pinia'
import { ElMessage } from 'element-plus'
import { useSettingsStore, THEMES } from '@/stores/settings'
import { useAuthStore } from '@/stores/auth'
import {
  fetchDatasources,
  createDatasource,
  updateDatasource,
  deleteDatasource,
  testDatasource,
} from '@/api/datasources'

const store = useSettingsStore()
const { theme, pollSeconds, notifyOnCritical } = storeToRefs(store)
const auth = useAuthStore()
const isAdmin = computed(() => auth.role === 'admin')

const POLL_PRESETS = [
  { s: 5, label: '5s' },
  { s: 10, label: '10s' },
  { s: 30, label: '30s' },
  { s: 60, label: '1m' },
]
const DS_TYPES = [
  { value: 'postgres', label: 'PostgreSQL' },
  { value: 'timescaledb', label: 'TimescaleDB' },
]
const SSL_MODES = ['disable', 'allow', 'prefer', 'require', 'verify-ca', 'verify-full']

const LED_BY_STATE = { testing: 'led--warn led--pulse', ok: 'led--ok', error: 'led--crit' }

// --- Acquisition prefs: dirty tracking (theme commits instantly; connections
//     save individually, so the commit bar governs poll/notify only) ---------
const fingerprint = () => JSON.stringify({ p: pollSeconds.value, n: notifyOnCritical.value })
const savedPrefs = ref('')
const dirty = computed(() => savedPrefs.value !== fingerprint())

function pickTheme(id) {
  store.applyTheme(id)
}
function setPoll(seconds) {
  pollSeconds.value = seconds
}
function commit() {
  store.savePrefs()
  savedPrefs.value = fingerprint()
  ElMessage.success('Settings committed')
}

// --- Data sources (server-side) --------------------------------------------
const datasources = ref([])
const dsLoading = ref(false)
const rowTest = reactive({}) // id -> { state, message }

const dialogVisible = ref(false)
const editingDsId = ref(null) // null = create
const savingDs = ref(false)
const blankDs = () => ({
  name: '',
  type: 'postgres',
  host: '127.0.0.1',
  port: 5432,
  database: '',
  db_schema: 'public',
  username: 'postgres',
  password: '',
  sslmode: 'prefer',
})
const dsForm = reactive(blankDs())
const dsTest = reactive({ state: 'idle', message: '' }) // idle|testing|ok|error

// Delete-confirmation dialog (mirrors LivePage's del-dialog).
const deleteDialogVisible = ref(false)
const deletingDs = ref(false)
const deleteTarget = ref(null)

const dsDialogTitle = computed(() => (editingDsId.value ? 'Edit connection' : 'Add connection'))
const dsTestLed = computed(() => LED_BY_STATE[dsTest.state] || '')
const editingHasPassword = computed(
  () => datasources.value.find((d) => d.id === editingDsId.value)?.has_password,
)
function rowLed(id) {
  return LED_BY_STATE[rowTest[id]?.state] || ''
}

async function loadDatasources() {
  dsLoading.value = true
  try {
    datasources.value = await fetchDatasources()
  } catch (e) {
    if (e?.response?.status !== 403) ElMessage.error('Failed to load connections.')
  } finally {
    dsLoading.value = false
  }
}

function openCreateDs() {
  editingDsId.value = null
  Object.assign(dsForm, blankDs())
  dsTest.state = 'idle'
  dsTest.message = ''
  dialogVisible.value = true
}
function openEditDs(ds) {
  editingDsId.value = ds.id
  Object.assign(dsForm, {
    name: ds.name,
    type: ds.type,
    host: ds.host,
    port: ds.port,
    database: ds.database,
    db_schema: ds.db_schema || 'public',
    username: ds.username,
    password: '', // blank = keep the stored secret
    sslmode: ds.sslmode,
  })
  dsTest.state = 'idle'
  dsTest.message = ''
  dialogVisible.value = true
}

async function testInDialog() {
  dsTest.state = 'testing'
  dsTest.message = 'Opening connection…'
  try {
    const r = await testDatasource({
      datasource_id: editingDsId.value ?? undefined,
      type: dsForm.type,
      host: dsForm.host,
      port: dsForm.port,
      database: dsForm.database,
      username: dsForm.username,
      password: dsForm.password || undefined,
      sslmode: dsForm.sslmode,
    })
    dsTest.state = r.ok ? 'ok' : 'error'
    dsTest.message = r.server_version ? `${r.message} · ${r.server_version}` : r.message
  } catch (e) {
    dsTest.state = 'error'
    dsTest.message = e?.response?.data?.detail || 'Test failed.'
  }
}

async function saveDs() {
  if (!dsForm.name.trim()) {
    ElMessage.warning('Name is required.')
    return
  }
  savingDs.value = true
  try {
    const payload = {
      name: dsForm.name.trim(),
      type: dsForm.type,
      host: dsForm.host.trim(),
      port: dsForm.port,
      database: dsForm.database.trim(),
      db_schema: dsForm.db_schema.trim() || 'public',
      username: dsForm.username.trim(),
      sslmode: dsForm.sslmode,
      ...(dsForm.password ? { password: dsForm.password } : {}),
    }
    if (editingDsId.value) {
      const updated = await updateDatasource(editingDsId.value, payload)
      const i = datasources.value.findIndex((d) => d.id === editingDsId.value)
      if (i !== -1) datasources.value[i] = updated
      ElMessage.success('Connection updated.')
    } else {
      const created = await createDatasource(payload)
      datasources.value.push(created)
      datasources.value.sort((a, b) => a.name.localeCompare(b.name))
      ElMessage.success('Connection saved.')
    }
    dialogVisible.value = false
  } catch (e) {
    ElMessage.error(e?.response?.data?.detail || 'Failed to save connection.')
  } finally {
    savingDs.value = false
  }
}

function removeDs(ds) {
  deleteTarget.value = ds
  deleteDialogVisible.value = true
}

async function confirmDeleteDs() {
  const ds = deleteTarget.value
  if (!ds) return
  deletingDs.value = true
  try {
    await deleteDatasource(ds.id)
    datasources.value = datasources.value.filter((d) => d.id !== ds.id)
    delete rowTest[ds.id]
    ElMessage.success('Connection deleted.')
    deleteDialogVisible.value = false
    deleteTarget.value = null
  } catch (e) {
    ElMessage.error(e?.response?.data?.detail || 'Delete failed.')
  } finally {
    deletingDs.value = false
  }
}

async function testRow(ds) {
  rowTest[ds.id] = { state: 'testing', message: 'Opening connection…' }
  try {
    const r = await testDatasource({ datasource_id: ds.id })
    rowTest[ds.id] = {
      state: r.ok ? 'ok' : 'error',
      message: r.server_version ? `${r.message} · ${r.server_version}` : r.message,
    }
  } catch (e) {
    rowTest[ds.id] = { state: 'error', message: e?.response?.data?.detail || 'Test failed.' }
  }
}

onMounted(async () => {
  savedPrefs.value = fingerprint()
  await loadDatasources()
})
</script>

<template>
  <div class="cfg">
    <!-- ── Console header ─────────────────────────────────────────────── -->
    <header class="cfg__head">
      <div>
        <p class="cfg__eyebrow">MML · SYSTEM CONFIGURATION</p>
        <h1 class="cfg__title">Console Settings</h1>
      </div>
      <div class="cfg__sync" :class="{ 'cfg__sync--dirty': dirty }">
        <span class="led" :class="dirty ? 'led--warn' : 'led--ok'"></span>
        {{ dirty ? 'UNSAVED CHANGES' : 'CONFIG SYNCED' }}
      </div>
    </header>

    <!-- ── Module 1 · Appearance ──────────────────────────────────────── -->
    <section class="mod">
      <header class="mod__head">
        <span class="mod__tag">Appearance</span>
        <span class="mod__sub">HMI color faceplate</span>
      </header>
      <div class="mod__body">
        <p class="fld__label">Color theme</p>
        <div class="plates" role="group" aria-label="Color theme">
          <button
            v-for="t in THEMES"
            :key="t.id"
            type="button"
            class="plate"
            :class="{ 'plate--active': theme === t.id }"
            :aria-pressed="theme === t.id"
            @click="pickTheme(t.id)"
          >
            <span class="plate__screen" :style="{ background: t.preview.bg }">
              <span
                class="plate__win"
                :style="{ background: t.preview.panel, borderColor: t.preview.accent }"
              >
                <span class="plate__accent" :style="{ background: t.preview.accent }"></span>
                <span class="plate__row" :style="{ background: t.preview.fg }"></span>
                <span
                  class="plate__row plate__row--short"
                  :style="{ background: t.preview.fg }"
                ></span>
                <span
                  class="plate__gauge"
                  :style="{
                    borderColor: t.preview.accent,
                    boxShadow: '0 0 10px ' + t.preview.accent + '66',
                  }"
                ></span>
              </span>
            </span>
            <span class="plate__foot">
              <span class="led" :class="theme === t.id ? 'led--ok' : ''"></span>
              <span class="plate__name">{{ t.name }}</span>
              <span class="plate__hex">{{ t.preview.accent }}</span>
            </span>
            <span class="plate__blurb">{{ t.blurb }}</span>
          </button>
        </div>
      </div>
    </section>

    <!-- ── Module 2 · Acquisition ─────────────────────────────────────── -->
    <section class="mod">
      <header class="mod__head">
        <span class="mod__tag">Acquisition</span>
        <span class="mod__sub">Default polling cadence</span>
      </header>
      <div class="mod__body acq">
        <div class="acq__row">
          <div class="acq__label">
            <p class="fld__label">Default poll interval</p>
            <p class="fld__hint">Sliding-window refresh used by Live &amp; Trends tiles.</p>
          </div>
          <div class="acq__ctl">
            <el-input-number v-model="pollSeconds" :min="1" :max="3600" controls-position="right" />
            <span class="acq__unit">seconds</span>
            <div class="chips">
              <button
                v-for="p in POLL_PRESETS"
                :key="p.s"
                type="button"
                class="chip"
                :class="{ 'chip--on': pollSeconds === p.s }"
                @click="setPoll(p.s)"
              >
                {{ p.label }}
              </button>
            </div>
          </div>
        </div>

        <div class="acq__row acq__row--divider">
          <div class="acq__label">
            <p class="fld__label">Critical-alarm notifications</p>
            <p class="fld__hint">Surface a desktop toast when a critical alarm trips.</p>
          </div>
          <div class="acq__ctl acq__ctl--switch">
            <span class="led" :class="notifyOnCritical ? 'led--crit' : ''"></span>
            <el-switch v-model="notifyOnCritical" />
            <span class="acq__state">{{ notifyOnCritical ? 'ARMED' : 'OFF' }}</span>
          </div>
        </div>
      </div>
    </section>

    <!-- ── Module 3 · Data sources ────────────────────────────────────── -->
    <section class="mod">
      <header class="mod__head">
        <span class="mod__tag">Data sources</span>
        <span class="mod__sub">Saved database connections</span>
        <el-button
          v-if="isAdmin"
          class="mod__action"
          type="primary"
          size="small"
          @click="openCreateDs"
        >
          + Add connection
        </el-button>
      </header>
      <div class="mod__body">
        <p v-if="!isAdmin" class="ds__readonly">
          <span class="led"></span> Only administrators can manage connections.
        </p>

        <div v-if="datasources.length" class="conns">
          <div v-for="ds in datasources" :key="ds.id" class="conn">
            <span class="led" :class="rowLed(ds.id)"></span>
            <div class="conn__main">
              <span class="conn__name">
                {{ ds.name }}
                <span class="conn__type">{{ ds.type }}</span>
              </span>
              <span class="conn__dsn">
                {{ ds.username }}@{{ ds.host }}:{{ ds.port }}/{{ ds.database }} · schema={{ ds.db_schema }} · sslmode={{ ds.sslmode }}
              </span>
              <span v-if="rowTest[ds.id]?.message" class="conn__result">{{
                rowTest[ds.id].message
              }}</span>
            </div>
            <div v-if="isAdmin" class="conn__actions">
              <el-button
                size="small"
                :loading="rowTest[ds.id]?.state === 'testing'"
                @click="testRow(ds)"
              >
                Test
              </el-button>
              <el-button size="small" @click="openEditDs(ds)">Edit</el-button>
              <el-button size="small" text type="danger" @click="removeDs(ds)">Delete</el-button>
            </div>
          </div>
        </div>

        <p v-else-if="!dsLoading" class="ds__empty">
          No saved connections yet.
          <template v-if="isAdmin">Add one to make it selectable when editing a Live panel.</template>
        </p>
      </div>
    </section>

    <!-- ── Commit bar (acquisition only) ──────────────────────────────── -->
    <div class="cfg__bar">
      <span class="cfg__barhint">
        Appearance applies instantly. Connections save on their own. Acquisition needs a commit.
      </span>
      <el-button type="primary" :disabled="!dirty" @click="commit">Save changes</el-button>
    </div>

    <!-- ── Connection editor dialog ───────────────────────────────────── -->
    <el-dialog v-model="dialogVisible" :title="dsDialogTitle" width="640px">
      <el-form label-position="top">
        <div class="ds__grid">
          <div class="fld fld--span6">
            <label class="fld__label" for="dsf-name">Name</label>
            <el-input id="dsf-name" v-model="dsForm.name" placeholder="e.g. Plant historian" />
          </div>
          <div class="fld fld--span2">
            <label class="fld__label" for="dsf-type">Type</label>
            <el-select id="dsf-type" v-model="dsForm.type">
              <el-option v-for="o in DS_TYPES" :key="o.value" :label="o.label" :value="o.value" />
            </el-select>
          </div>
          <div class="fld fld--span3">
            <label class="fld__label" for="dsf-host">Host</label>
            <el-input id="dsf-host" v-model="dsForm.host" placeholder="127.0.0.1" />
          </div>
          <div class="fld">
            <label class="fld__label" for="dsf-port">Port</label>
            <el-input-number
              id="dsf-port"
              v-model="dsForm.port"
              :min="1"
              :max="65535"
              :controls="false"
            />
          </div>
          <div class="fld fld--span2">
            <label class="fld__label" for="dsf-db">Database</label>
            <el-input id="dsf-db" v-model="dsForm.database" placeholder="mml" />
          </div>
          <div class="fld fld--span2">
            <label class="fld__label" for="dsf-schema">Schema</label>
            <el-input id="dsf-schema" v-model="dsForm.db_schema" placeholder="public" />
          </div>
          <div class="fld fld--span2">
            <label class="fld__label" for="dsf-ssl">SSL mode</label>
            <el-select id="dsf-ssl" v-model="dsForm.sslmode">
              <el-option v-for="m in SSL_MODES" :key="m" :label="m" :value="m" />
            </el-select>
          </div>
          <div class="fld fld--span3">
            <label class="fld__label" for="dsf-user">Username</label>
            <el-input id="dsf-user" v-model="dsForm.username" placeholder="postgres" />
          </div>
          <div class="fld fld--span3">
            <label class="fld__label" for="dsf-pass">Password</label>
            <el-input
              id="dsf-pass"
              v-model="dsForm.password"
              type="password"
              show-password
              :placeholder="editingHasPassword ? '•••••• (unchanged)' : '••••••••'"
            />
          </div>
        </div>
      </el-form>

      <template #footer>
        <div class="ds-dialog__foot">
          <el-button :loading="dsTest.state === 'testing'" @click="testInDialog">
            Test connection
          </el-button>
          <p class="ds__status" :class="{ 'ds__status--show': dsTest.state !== 'idle' }">
            <span class="led" :class="dsTestLed"></span>
            <span class="ds__msg">{{ dsTest.message }}</span>
          </p>
          <span class="ds-dialog__spacer"></span>
          <el-button @click="dialogVisible = false">Cancel</el-button>
          <el-button type="primary" :loading="savingDs" @click="saveDs">Save</el-button>
        </div>
      </template>
    </el-dialog>

    <!-- Delete connection: small centred confirm dialog (matches LivePage) -->
    <el-dialog
      v-model="deleteDialogVisible"
      title="Delete connection"
      width="420px"
      align-center
      append-to-body
      class="del-dialog"
    >
      <p v-if="deleteTarget" class="del-dialog__msg">
        Delete <strong>{{ deleteTarget.name }}</strong>?
      </p>
      <p class="del-dialog__hint">
        Panels bound to it fall back to the app database. This cannot be undone.
      </p>
      <template #footer>
        <el-button @click="deleteDialogVisible = false">Cancel</el-button>
        <el-button type="danger" :loading="deletingDs" @click="confirmDeleteDs">Delete</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<style scoped>
.cfg {
  --plate-radius: 10px;
  display: flex;
  flex-direction: column;
  gap: var(--space-5);
  max-width: 1500px;
  padding-bottom: 88px;
}

/* ── Header ─────────────────────────────────────────────────────────── */
.cfg__head {
  display: flex;
  align-items: flex-end;
  justify-content: space-between;
  gap: var(--space-4);
  flex-wrap: wrap;
}
.cfg__eyebrow {
  margin: 0 0 6px;
  font-family: var(--font-mono);
  font-size: 11px;
  letter-spacing: 0.22em;
  text-transform: uppercase;
  color: var(--fg-dim);
}
.cfg__title {
  margin: 0;
  font-family: var(--font-display);
  font-size: 34px;
  font-weight: 700;
  letter-spacing: 0.01em;
  line-height: 1;
  color: var(--fg);
}
.cfg__sync {
  display: inline-flex;
  align-items: center;
  gap: var(--space-2);
  padding: 6px 12px;
  border: 1px solid var(--border);
  border-radius: 999px;
  background: var(--bg-panel);
  font-family: var(--font-mono);
  font-size: 11px;
  letter-spacing: 0.12em;
  color: var(--fg-muted);
}

/* ── Rack module ────────────────────────────────────────────────────── */
.mod {
  position: relative;
  background: var(--bg-panel);
  border: 1px solid var(--border-soft);
  border-radius: var(--radius-lg);
  overflow: hidden;
}
.mod::before {
  content: '';
  position: absolute;
  inset: 0 0 auto 0;
  height: 2px;
  background: linear-gradient(90deg, var(--accent), transparent 65%);
  opacity: 0.7;
}
.mod__head {
  display: flex;
  align-items: baseline;
  gap: var(--space-3);
  padding: var(--space-4) var(--space-5);
  border-bottom: 1px solid var(--border-soft);
}
.mod__tag {
  font-family: var(--font-display);
  font-size: 13px;
  font-weight: 600;
  letter-spacing: 0.16em;
  text-transform: uppercase;
  color: var(--fg);
}
.mod__sub {
  font-family: var(--font-mono);
  font-size: 12px;
  color: var(--fg-dim);
}
.mod__action {
  margin-left: auto;
  align-self: center;
}
.mod__body {
  padding: var(--space-5);
}

.fld__label {
  display: block;
  margin: 0 0 8px;
  font-family: var(--font-mono);
  font-size: 11px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--fg-muted);
}
.fld__hint {
  margin: 4px 0 0;
  font-size: 12.5px;
  color: var(--fg-dim);
}

/* ── Signature: theme faceplates ────────────────────────────────────── */
.plates {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--space-4);
}
.plate {
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding: 10px;
  background: var(--bg-elev);
  border: 1px solid var(--border);
  border-radius: var(--plate-radius);
  cursor: pointer;
  text-align: left;
  transition: transform 0.16s ease, border-color 0.16s ease, box-shadow 0.16s ease;
}
.plate:hover {
  transform: translateY(-2px);
  border-color: var(--fg-dim);
}
.plate--active {
  border-color: var(--accent);
  box-shadow: 0 0 0 1px var(--accent), 0 8px 24px -10px var(--accent);
}
.plate__screen {
  position: relative;
  display: block;
  height: 84px;
  border-radius: 7px;
  padding: 10px;
  overflow: hidden;
}
.plate__win {
  position: relative;
  display: block;
  height: 100%;
  border: 1px solid;
  border-radius: 5px;
  padding: 9px;
}
.plate__accent {
  display: block;
  width: 34px;
  height: 4px;
  border-radius: 2px;
  margin-bottom: 8px;
}
.plate__row {
  display: block;
  width: 70%;
  height: 4px;
  border-radius: 2px;
  margin-bottom: 5px;
  opacity: 0.32;
}
.plate__row--short {
  width: 45%;
  opacity: 0.18;
}
.plate__gauge {
  position: absolute;
  right: 9px;
  bottom: 8px;
  width: 22px;
  height: 22px;
  border: 2px solid;
  border-radius: 50%;
}
.plate__foot {
  display: flex;
  align-items: center;
  gap: 8px;
}
.plate__name {
  font-family: var(--font-display);
  font-size: 14px;
  font-weight: 600;
  letter-spacing: 0.04em;
  color: var(--fg);
}
.plate__hex {
  margin-left: auto;
  font-family: var(--font-mono);
  font-size: 11px;
  color: var(--fg-dim);
}
.plate__blurb {
  font-size: 12px;
  color: var(--fg-dim);
}

/* ── Acquisition ────────────────────────────────────────────────────── */
.acq__row {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: var(--space-5);
}
.acq__row--divider {
  margin-top: var(--space-5);
  padding-top: var(--space-5);
  border-top: 1px solid var(--border-soft);
}
.acq__label {
  max-width: 360px;
}
.acq__label .fld__label {
  margin-bottom: 0;
}
.acq__ctl {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  flex-wrap: wrap;
  justify-content: flex-end;
}
.acq__unit {
  font-family: var(--font-mono);
  font-size: 12px;
  color: var(--fg-dim);
}
.acq__state {
  font-family: var(--font-mono);
  font-size: 11px;
  letter-spacing: 0.1em;
  color: var(--fg-muted);
}
.chips {
  display: inline-flex;
  gap: 6px;
}
.chip {
  padding: 5px 11px;
  font-family: var(--font-mono);
  font-size: 12px;
  color: var(--fg-muted);
  background: var(--bg-elev);
  border: 1px solid var(--border);
  border-radius: 999px;
  cursor: pointer;
  transition: color 0.14s ease, border-color 0.14s ease, background 0.14s ease;
}
.chip:hover {
  color: var(--fg);
  border-color: var(--fg-dim);
}
.chip--on {
  color: var(--accent);
  border-color: var(--accent);
  background: var(--accent-soft);
}

/* ── Data sources ───────────────────────────────────────────────────── */
.ds__readonly,
.ds__empty {
  display: flex;
  align-items: center;
  gap: 8px;
  margin: 0;
  font-size: 13px;
  color: var(--fg-dim);
}
.conns {
  display: flex;
  flex-direction: column;
  gap: var(--space-3);
}
.conn {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  padding: var(--space-3) var(--space-4);
  background: var(--bg-elev);
  border: 1px solid var(--border);
  border-radius: var(--radius);
}
.conn__main {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 3px;
}
.conn__name {
  display: flex;
  align-items: center;
  gap: 8px;
  font-family: var(--font-display);
  font-size: 14px;
  font-weight: 600;
  letter-spacing: 0.03em;
  color: var(--fg);
}
.conn__type {
  font-family: var(--font-mono);
  font-size: 10px;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  padding: 2px 6px;
  border: 1px solid var(--border);
  border-radius: 4px;
  color: var(--fg-muted);
}
.conn__dsn {
  font-family: var(--font-mono);
  font-size: 12px;
  color: var(--fg-dim);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.conn__result {
  font-family: var(--font-mono);
  font-size: 11.5px;
  color: var(--fg-muted);
}
.conn__actions {
  margin-left: auto;
  display: inline-flex;
  gap: 6px;
  align-items: center;
  flex: none;
}

/* form grid shared by the datasource dialog */
.ds__grid {
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  gap: var(--space-4);
}
.fld {
  grid-column: span 6;
  min-width: 0;
}
.fld--span2 {
  grid-column: span 2;
}
.fld--span3 {
  grid-column: span 3;
}
.fld--span6 {
  grid-column: span 6;
}
.fld :deep(.el-input),
.fld :deep(.el-select),
.fld :deep(.el-input-number) {
  width: 100%;
}
.fld :deep(.el-input-number .el-input__inner) {
  text-align: left;
}
.ds__status {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  margin: 0;
  opacity: 0;
  transition: opacity 0.18s ease;
}
.ds__status--show {
  opacity: 1;
}
.ds__msg {
  font-family: var(--font-mono);
  font-size: 12.5px;
  color: var(--fg-muted);
}
.ds-dialog__foot {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  width: 100%;
}
.ds-dialog__spacer {
  margin-left: auto;
}

/* ── Delete-connection dialog (mirrors LivePage's del-dialog) ─────────── */
.del-dialog__msg {
  margin: 0 0 var(--space-2) 0;
  font-size: 14px;
  color: var(--fg);
}
.del-dialog__hint {
  margin: 0;
  font-size: 12px;
  color: var(--fg-muted);
}

/* ── Status LEDs ────────────────────────────────────────────────────── */
.led {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: var(--fg-dim);
  flex: none;
}
.led--ok {
  background: var(--ok);
  box-shadow: 0 0 8px var(--ok);
}
.led--warn {
  background: var(--warn);
  box-shadow: 0 0 8px var(--warn);
}
.led--crit {
  background: var(--crit);
  box-shadow: 0 0 8px var(--crit);
}
.led--pulse {
  animation: led-pulse 0.9s ease-in-out infinite;
}
@keyframes led-pulse {
  0%,
  100% {
    opacity: 1;
  }
  50% {
    opacity: 0.35;
  }
}

/* ── Commit bar ─────────────────────────────────────────────────────── */
.cfg__bar {
  position: sticky;
  bottom: calc(-1 * var(--space-6));
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: var(--space-4);
  margin: var(--space-2) calc(-1 * var(--space-6)) calc(-1 * var(--space-6));
  padding: var(--space-4) var(--space-6);
  background: color-mix(in srgb, var(--bg-app) 86%, transparent);
  border-top: 1px solid var(--border);
  backdrop-filter: blur(8px);
}
.cfg__barhint {
  margin-right: auto;
  font-size: 12.5px;
  color: var(--fg-dim);
}

@media (max-width: 720px) {
  .plates {
    grid-template-columns: 1fr;
  }
  .acq__row {
    flex-direction: column;
    gap: var(--space-3);
  }
  .acq__ctl {
    justify-content: flex-start;
  }
  .fld--span2,
  .fld--span3 {
    grid-column: span 6;
  }
  .conn__actions {
    margin-left: 0;
  }
}

@media (prefers-reduced-motion: reduce) {
  .plate,
  .chip,
  .ds__status {
    transition: none;
  }
  .led--pulse {
    animation: none;
  }
}
</style>

// scada-frontend/src/pages/SettingsPage.jsx
import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Controller, useForm } from 'react-hook-form'
import TextField from '@mui/material/TextField'
import Select from '@mui/material/Select'
import MenuItem from '@mui/material/MenuItem'
import FormControl from '@mui/material/FormControl'
import InputLabel from '@mui/material/InputLabel'
import Switch from '@mui/material/Switch'
import Button from '@mui/material/Button'
import IconButton from '@mui/material/IconButton'
import InputAdornment from '@mui/material/InputAdornment'
import Dialog from '@mui/material/Dialog'
import DialogTitle from '@mui/material/DialogTitle'
import DialogContent from '@mui/material/DialogContent'
import DialogActions from '@mui/material/DialogActions'
import Alert from '@mui/material/Alert'
import Snackbar from '@mui/material/Snackbar'
import ChevronRightRounded from '@mui/icons-material/ChevronRightRounded'
import VisibilityOutlined from '@mui/icons-material/VisibilityOutlined'
import VisibilityOffOutlined from '@mui/icons-material/VisibilityOffOutlined'
import { useSettingsStore, THEMES } from '@/stores/settings'
import { useAuthStore } from '@/stores/auth'
import {
  fetchDatasources, createDatasource, updateDatasource, deleteDatasource, testDatasource,
} from '@/api/datasources'
import styles from './SettingsPage.module.css'

/**
 * SettingsPage — the control-console for portal-wide parameters (route: /settings).
 * Laid out as rack modules: APPEARANCE (color faceplate), ACQUISITION (poll
 * cadence + alerts), and DATA SOURCES (admin-managed saved DB connections).
 * Ported from SettingsPage.vue.
 *
 * Theme applies live via the settings store's applyTheme(); acquisition
 * prefs (pollSeconds/notifyOnCritical) are bound directly to the same store
 * (mirroring Pinia's mutable refs via useSettingsStore.setState) and only
 * persisted to localStorage when the commit bar's "Save changes" is clicked.
 * Connections live server-side (api/datasources) — list via TanStack Query,
 * each row/dialog can "Test connection" independently and saves on its own.
 */

const POLL_PRESETS = [
  { s: 5, label: '5s' },
  { s: 10, label: '10s' },
  { s: 30, label: '30s' },
  { s: 60, label: '1m' },
]
const DS_TYPES = [
  { value: 'postgres', label: 'PostgreSQL' },
  { value: 'timescaledb', label: 'TimescaleDB' },
]
const SSL_MODES = ['disable', 'allow', 'prefer', 'require', 'verify-ca', 'verify-full']

const BLANK_DS = {
  name: '',
  type: 'postgres',
  host: '127.0.0.1',
  port: 5432,
  database: '',
  db_schema: 'public',
  username: 'postgres',
  password: '',
  sslmode: 'prefer',
}

function ledClass(kind) {
  if (kind === 'ok') return `${styles.led} ${styles.ledOk}`
  if (kind === 'warn') return `${styles.led} ${styles.ledWarn}`
  if (kind === 'crit') return `${styles.led} ${styles.ledCrit}`
  return styles.led
}

// Maps a test-connection async state (idle|testing|ok|error) to a LED class.
function testLedClass(state) {
  if (state === 'testing') return `${styles.led} ${styles.ledWarn} ${styles.ledPulse}`
  if (state === 'ok') return `${styles.led} ${styles.ledOk}`
  if (state === 'error') return `${styles.led} ${styles.ledCrit}`
  return styles.led
}

// pollSeconds/notifyOnCritical have no dedicated setter actions on the
// settings store (by design — see stores/settings.js) since Pinia's version
// bound them as directly-mutable refs. Zustand's store instance always
// exposes setState(), so this is the direct equivalent, kept local to this
// page since nothing else needs to write these fields pre-commit.
function setPollSeconds(v) {
  useSettingsStore.setState({ pollSeconds: v })
}
function setNotifyOnCritical(v) {
  useSettingsStore.setState({ notifyOnCritical: v })
}

export default function SettingsPage() {
  const theme = useSettingsStore((s) => s.theme)
  const applyTheme = useSettingsStore((s) => s.applyTheme)
  const pollSeconds = useSettingsStore((s) => s.pollSeconds)
  const notifyOnCritical = useSettingsStore((s) => s.notifyOnCritical)
  const savePrefsAction = useSettingsStore((s) => s.savePrefs)
  const role = useAuthStore((s) => s.user?.role ?? null)
  const isAdmin = role === 'admin'

  const [collapsed, setCollapsed] = useState({ appearance: true, acquisition: true, datasources: true })
  function toggle(key) {
    setCollapsed((c) => ({ ...c, [key]: !c[key] }))
  }

  const [snackbar, setSnackbar] = useState({ open: false, message: '', severity: 'success' })
  function notify(message, severity = 'success') {
    setSnackbar({ open: true, message, severity })
  }

  // --- Acquisition prefs: dirty tracking (theme commits instantly; connections
  //     save individually, so the commit bar governs poll/notify only) ---------
  const fingerprint = `${pollSeconds}|${notifyOnCritical}`
  const [savedPrefs, setSavedPrefs] = useState(fingerprint)
  const dirty = savedPrefs !== fingerprint

  function commit() {
    savePrefsAction()
    setSavedPrefs(fingerprint)
    notify('Settings committed')
  }

  // --- Data sources (server-side) --------------------------------------------
  const queryClient = useQueryClient()
  const {
    data: datasourcesRaw = [],
    isLoading: dsLoading,
    error: dsError,
  } = useQuery({ queryKey: ['datasources'], queryFn: fetchDatasources })
  const datasources = useMemo(
    () => [...datasourcesRaw].sort((a, b) => a.name.localeCompare(b.name)),
    [datasourcesRaw],
  )
  const invalidateDatasources = () => queryClient.invalidateQueries({ queryKey: ['datasources'] })

  const [rowTest, setRowTest] = useState({}) // id -> { state, message }

  const [dsDialogOpen, setDsDialogOpen] = useState(false)
  const [editingDsId, setEditingDsId] = useState(null) // null = create
  const [dsDialogError, setDsDialogError] = useState('')
  const [dsTest, setDsTest] = useState({ state: 'idle', message: '' })
  const [showPassword, setShowPassword] = useState(false)

  const {
    register, handleSubmit, reset, control, getValues,
    formState: { errors },
  } = useForm({ defaultValues: BLANK_DS })

  const dsDialogTitle = editingDsId ? 'Edit connection' : 'Add connection'
  const editingHasPassword = useMemo(
    () => datasources.find((d) => d.id === editingDsId)?.has_password,
    [datasources, editingDsId],
  )

  const createMutation = useMutation({
    mutationFn: createDatasource,
    onSuccess: () => {
      invalidateDatasources()
      notify('Connection saved.')
      setDsDialogOpen(false)
    },
    onError: (e) => setDsDialogError(e?.response?.data?.detail || 'Failed to save connection.'),
  })
  const updateMutation = useMutation({
    mutationFn: ({ id, payload }) => updateDatasource(id, payload),
    onSuccess: () => {
      invalidateDatasources()
      notify('Connection updated.')
      setDsDialogOpen(false)
    },
    onError: (e) => setDsDialogError(e?.response?.data?.detail || 'Failed to save connection.'),
  })
  const deleteMutation = useMutation({
    mutationFn: (id) => deleteDatasource(id),
    onSuccess: (_data, id) => {
      invalidateDatasources()
      setRowTest((prev) => {
        const next = { ...prev }
        delete next[id]
        return next
      })
      notify('Connection deleted.')
      setDeleteTarget(null)
    },
    onError: (e) => setDeleteError(e?.response?.data?.detail || 'Delete failed.'),
  })
  const savingDs = createMutation.isPending || updateMutation.isPending

  function openCreateDs() {
    setEditingDsId(null)
    setDsDialogError('')
    reset(BLANK_DS)
    setDsTest({ state: 'idle', message: '' })
    setShowPassword(false)
    setDsDialogOpen(true)
  }
  function openEditDs(ds) {
    setEditingDsId(ds.id)
    setDsDialogError('')
    reset({
      name: ds.name,
      type: ds.type,
      host: ds.host,
      port: ds.port,
      database: ds.database,
      db_schema: ds.db_schema || 'public',
      username: ds.username,
      password: '', // blank = keep the stored secret
      sslmode: ds.sslmode,
    })
    setDsTest({ state: 'idle', message: '' })
    setShowPassword(false)
    setDsDialogOpen(true)
  }

  async function testInDialog() {
    setDsTest({ state: 'testing', message: 'Opening connection…' })
    const v = getValues()
    try {
      const r = await testDatasource({
        datasource_id: editingDsId ?? undefined,
        type: v.type,
        host: v.host,
        port: v.port,
        database: v.database,
        username: v.username,
        password: v.password || undefined,
        sslmode: v.sslmode,
      })
      setDsTest({
        state: r.ok ? 'ok' : 'error',
        message: r.server_version ? `${r.message} · ${r.server_version}` : r.message,
      })
    } catch (e) {
      setDsTest({ state: 'error', message: e?.response?.data?.detail || 'Test failed.' })
    }
  }

  function onSaveDs(values) {
    setDsDialogError('')
    const payload = {
      name: values.name.trim(),
      type: values.type,
      host: values.host.trim(),
      port: values.port,
      database: values.database.trim(),
      db_schema: (values.db_schema || '').trim() || 'public',
      username: values.username.trim(),
      sslmode: values.sslmode,
      ...(values.password ? { password: values.password } : {}),
    }
    if (editingDsId) updateMutation.mutate({ id: editingDsId, payload })
    else createMutation.mutate(payload)
  }

  async function testRow(ds) {
    setRowTest((prev) => ({ ...prev, [ds.id]: { state: 'testing', message: 'Opening connection…' } }))
    try {
      const r = await testDatasource({ datasource_id: ds.id })
      setRowTest((prev) => ({
        ...prev,
        [ds.id]: {
          state: r.ok ? 'ok' : 'error',
          message: r.server_version ? `${r.message} · ${r.server_version}` : r.message,
        },
      }))
    } catch (e) {
      setRowTest((prev) => ({
        ...prev,
        [ds.id]: { state: 'error', message: e?.response?.data?.detail || 'Test failed.' },
      }))
    }
  }

  // Delete-confirmation dialog (mirrors AccountsPage / LivePage's del-dialog).
  const [deleteTarget, setDeleteTarget] = useState(null)
  const [deleteError, setDeleteError] = useState('')
  function openDeleteDs(ds) {
    setDeleteError('')
    setDeleteTarget(ds)
  }
  function confirmDeleteDs() {
    if (deleteTarget) deleteMutation.mutate(deleteTarget.id)
  }

  return (
    <div className={styles.cfg}>
      {/* ── Console header ─────────────────────────────────────────────── */}
      <header className={styles.cfgHead}>
        <div>
          <p className={styles.cfgEyebrow}>MML · SYSTEM CONFIGURATION</p>
          <h1 className={styles.cfgTitle}>Console Settings</h1>
        </div>
        <div className={styles.cfgSync}>
          <span className={ledClass(dirty ? 'warn' : 'ok')} />
          {dirty ? 'UNSAVED CHANGES' : 'CONFIG SYNCED'}
        </div>
      </header>

      {/* ── Module 1 · Appearance ──────────────────────────────────────── */}
      <section className={`${styles.mod} ${collapsed.appearance ? styles.modCollapsed : ''}`}>
        <header className={styles.modHead} onClick={() => toggle('appearance')}>
          <span className={styles.modTag}>Appearance</span>
          <span className={styles.modSub}>HMI color faceplate</span>
          <ChevronRightRounded
            className={`${styles.modChevron} ${!collapsed.appearance ? styles.modChevronOpen : ''}`}
          />
        </header>
        {!collapsed.appearance && (
          <div className={styles.modBody}>
            <p className={styles.fldLabel}>Color theme</p>
            <div className={styles.plates} role="group" aria-label="Color theme">
              {THEMES.map((t) => (
                <button
                  key={t.id}
                  type="button"
                  className={`${styles.plate} ${theme === t.id ? styles.plateActive : ''}`}
                  aria-pressed={theme === t.id}
                  onClick={() => applyTheme(t.id)}
                >
                  <span className={styles.plateScreen} style={{ background: t.preview.bg }}>
                    <span
                      className={styles.plateWin}
                      style={{ background: t.preview.panel, borderColor: t.preview.accent }}
                    >
                      <span className={styles.plateAccent} style={{ background: t.preview.accent }} />
                      <span className={styles.plateRow} style={{ background: t.preview.fg }} />
                      <span
                        className={`${styles.plateRow} ${styles.plateRowShort}`}
                        style={{ background: t.preview.fg }}
                      />
                      <span
                        className={styles.plateGauge}
                        style={{
                          borderColor: t.preview.accent,
                          boxShadow: `0 0 10px ${t.preview.accent}66`,
                        }}
                      />
                    </span>
                  </span>
                  <span className={styles.plateFoot}>
                    <span className={ledClass(theme === t.id ? 'ok' : '')} />
                    <span className={styles.plateName}>{t.name}</span>
                    <span className={styles.plateHex}>{t.preview.accent}</span>
                  </span>
                  <span className={styles.plateBlurb}>{t.blurb}</span>
                </button>
              ))}
            </div>
          </div>
        )}
      </section>

      {/* ── Module 2 · Acquisition ─────────────────────────────────────── */}
      <section className={`${styles.mod} ${collapsed.acquisition ? styles.modCollapsed : ''}`}>
        <header className={styles.modHead} onClick={() => toggle('acquisition')}>
          <span className={styles.modTag}>Acquisition</span>
          <span className={styles.modSub}>Default polling cadence</span>
          <ChevronRightRounded
            className={`${styles.modChevron} ${!collapsed.acquisition ? styles.modChevronOpen : ''}`}
          />
        </header>
        {!collapsed.acquisition && (
          <div className={styles.modBody}>
            <div className={styles.acqRow}>
              <div className={styles.acqLabel}>
                <p className={styles.fldLabel}>Default poll interval</p>
                <p className={styles.fldHint}>Sliding-window refresh used by Live &amp; Trends tiles.</p>
              </div>
              <div className={styles.acqCtl}>
                <TextField
                  size="small"
                  type="number"
                  className={styles.pollField}
                  value={pollSeconds}
                  slotProps={{ htmlInput: { min: 1, max: 3600 } }}
                  onChange={(e) => {
                    const raw = e.target.value
                    // Never coerce a transiently-blank number field to 0 —
                    // ignore until a real digit lands (matches el-input-number's
                    // clamped-to-min behaviour rather than MUI's Number('')===0).
                    if (raw === '') return
                    const n = Number(raw)
                    if (Number.isFinite(n)) setPollSeconds(Math.min(3600, Math.max(1, Math.round(n))))
                  }}
                />
                <span className={styles.acqUnit}>seconds</span>
                <div className={styles.chips}>
                  {POLL_PRESETS.map((p) => (
                    <button
                      key={p.s}
                      type="button"
                      className={`${styles.chip} ${pollSeconds === p.s ? styles.chipOn : ''}`}
                      onClick={() => setPollSeconds(p.s)}
                    >
                      {p.label}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            <div className={`${styles.acqRow} ${styles.acqRowDivider}`}>
              <div className={styles.acqLabel}>
                <p className={styles.fldLabel}>Critical-alarm notifications</p>
                <p className={styles.fldHint}>Surface a desktop toast when a critical alarm trips.</p>
              </div>
              <div className={styles.acqCtl}>
                <span className={ledClass(notifyOnCritical ? 'crit' : '')} />
                <Switch
                  checked={notifyOnCritical}
                  onChange={(e) => setNotifyOnCritical(e.target.checked)}
                />
                <span className={styles.acqState}>{notifyOnCritical ? 'ARMED' : 'OFF'}</span>
              </div>
            </div>
          </div>
        )}
      </section>

      {/* ── Module 3 · Data sources ────────────────────────────────────── */}
      <section className={`${styles.mod} ${collapsed.datasources ? styles.modCollapsed : ''}`}>
        <header className={styles.modHead} onClick={() => toggle('datasources')}>
          <span className={styles.modTag}>Data sources</span>
          <span className={styles.modSub}>Saved database connections</span>
          {isAdmin && (
            <Button
              className={styles.modAction}
              variant="contained"
              size="small"
              onClick={(e) => {
                e.stopPropagation()
                openCreateDs()
              }}
            >
              + Add connection
            </Button>
          )}
          <ChevronRightRounded
            className={`${styles.modChevron} ${!collapsed.datasources ? styles.modChevronOpen : ''}`}
          />
        </header>
        {!collapsed.datasources && (
          <div className={styles.modBody}>
            {!isAdmin && (
              <p className={styles.dsReadonly}>
                <span className={styles.led} /> Only administrators can manage connections.
              </p>
            )}

            {dsError && dsError?.response?.status !== 403 && (
              <Alert severity="error">Failed to load connections.</Alert>
            )}

            {datasources.length > 0 ? (
              <div className={styles.conns}>
                {datasources.map((ds) => (
                  <div className={styles.conn} key={ds.id}>
                    <span className={testLedClass(rowTest[ds.id]?.state)} />
                    <div className={styles.connMain}>
                      <span className={styles.connName}>
                        {ds.name}
                        <span className={styles.connType}>{ds.type}</span>
                      </span>
                      <span className={styles.connDsn}>
                        {ds.username}@{ds.host}:{ds.port}/{ds.database} · schema={ds.db_schema} · sslmode=
                        {ds.sslmode}
                      </span>
                      {rowTest[ds.id]?.message && (
                        <span className={styles.connResult}>{rowTest[ds.id].message}</span>
                      )}
                    </div>
                    {isAdmin && (
                      <div className={styles.connActions}>
                        <Button
                          size="small"
                          loading={rowTest[ds.id]?.state === 'testing'}
                          onClick={() => testRow(ds)}
                        >
                          Test
                        </Button>
                        <Button size="small" onClick={() => openEditDs(ds)}>
                          Edit
                        </Button>
                        <Button size="small" color="error" onClick={() => openDeleteDs(ds)}>
                          Delete
                        </Button>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            ) : (
              !dsLoading && (
                <p className={styles.dsEmpty}>
                  No saved connections yet.
                  {isAdmin && ' Add one to make it selectable when editing a Live panel.'}
                </p>
              )
            )}
          </div>
        )}
      </section>

      {/* ── Commit bar (acquisition only) ──────────────────────────────── */}
      <div className={styles.cfgBar}>
        <span className={styles.cfgBarhint}>
          Appearance applies instantly. Connections save on their own. Acquisition needs a commit.
        </span>
        <Button variant="contained" disabled={!dirty} onClick={commit}>
          Save changes
        </Button>
      </div>

      {/* ── Connection editor dialog ───────────────────────────────────── */}
      <Dialog open={dsDialogOpen} onClose={() => setDsDialogOpen(false)} fullWidth maxWidth="sm">
        <DialogTitle>{dsDialogTitle}</DialogTitle>
        <form onSubmit={handleSubmit(onSaveDs)}>
          <DialogContent sx={{ pt: '8px !important' }}>
            <div className={styles.dsGrid}>
              <div className={`${styles.fld} ${styles.fldSpan6}`}>
                <TextField
                  label="Name"
                  placeholder="e.g. Plant historian"
                  fullWidth
                  size="small"
                  error={!!errors.name}
                  helperText={errors.name ? 'Name is required.' : ' '}
                  {...register('name', { required: true })}
                />
              </div>
              <div className={`${styles.fld} ${styles.fldSpan2}`}>
                <FormControl fullWidth size="small">
                  <InputLabel id="dsf-type-label">Type</InputLabel>
                  <Controller
                    name="type"
                    control={control}
                    render={({ field }) => (
                      <Select labelId="dsf-type-label" label="Type" {...field}>
                        {DS_TYPES.map((o) => (
                          <MenuItem key={o.value} value={o.value}>{o.label}</MenuItem>
                        ))}
                      </Select>
                    )}
                  />
                </FormControl>
              </div>
              <div className={`${styles.fld} ${styles.fldSpan3}`}>
                <TextField
                  label="Host"
                  placeholder="127.0.0.1"
                  fullWidth
                  size="small"
                  error={!!errors.host}
                  helperText={errors.host ? 'Host is required.' : ' '}
                  {...register('host', { required: true })}
                />
              </div>
              <div className={styles.fld}>
                <TextField
                  label="Port"
                  type="number"
                  fullWidth
                  size="small"
                  slotProps={{ htmlInput: { min: 1, max: 65535 } }}
                  error={!!errors.port}
                  helperText={errors.port ? 'Port must be 1–65535.' : ' '}
                  {...register('port', {
                    required: true,
                    valueAsNumber: true,
                    validate: (v) => (Number.isFinite(v) && v >= 1 && v <= 65535),
                  })}
                />
              </div>
              <div className={`${styles.fld} ${styles.fldSpan2}`}>
                <TextField
                  label="Database"
                  placeholder="mml"
                  fullWidth
                  size="small"
                  error={!!errors.database}
                  helperText={errors.database ? 'Database is required.' : ' '}
                  {...register('database', { required: true })}
                />
              </div>
              <div className={`${styles.fld} ${styles.fldSpan2}`}>
                <TextField
                  label="Schema"
                  placeholder="public"
                  fullWidth
                  size="small"
                  {...register('db_schema')}
                />
              </div>
              <div className={`${styles.fld} ${styles.fldSpan2}`}>
                <FormControl fullWidth size="small">
                  <InputLabel id="dsf-ssl-label">SSL mode</InputLabel>
                  <Controller
                    name="sslmode"
                    control={control}
                    render={({ field }) => (
                      <Select labelId="dsf-ssl-label" label="SSL mode" {...field}>
                        {SSL_MODES.map((m) => (
                          <MenuItem key={m} value={m}>{m}</MenuItem>
                        ))}
                      </Select>
                    )}
                  />
                </FormControl>
              </div>
              <div className={`${styles.fld} ${styles.fldSpan3}`}>
                <TextField
                  label="Username"
                  placeholder="postgres"
                  fullWidth
                  size="small"
                  error={!!errors.username}
                  helperText={errors.username ? 'Username is required.' : ' '}
                  {...register('username', { required: true })}
                />
              </div>
              <div className={`${styles.fld} ${styles.fldSpan3}`}>
                <TextField
                  label="Password"
                  type={showPassword ? 'text' : 'password'}
                  fullWidth
                  size="small"
                  placeholder={editingHasPassword ? '•••••• (unchanged)' : '••••••••'}
                  slotProps={{
                    input: {
                      endAdornment: (
                        <InputAdornment position="end">
                          <IconButton
                            size="small"
                            tabIndex={-1}
                            aria-label={showPassword ? 'Hide password' : 'Show password'}
                            onClick={() => setShowPassword((s) => !s)}
                          >
                            {showPassword ? <VisibilityOffOutlined fontSize="small" /> : <VisibilityOutlined fontSize="small" />}
                          </IconButton>
                        </InputAdornment>
                      ),
                    },
                  }}
                  {...register('password')}
                />
              </div>
            </div>
            {dsDialogError && <Alert severity="error" sx={{ mt: 2 }}>{dsDialogError}</Alert>}
          </DialogContent>

          <DialogActions>
            <div className={styles.dsDialogFoot}>
              <Button loading={dsTest.state === 'testing'} onClick={testInDialog}>
                Test connection
              </Button>
              <p className={`${styles.dsStatus} ${dsTest.state !== 'idle' ? styles.dsStatusShow : ''}`}>
                <span className={testLedClass(dsTest.state)} />
                <span className={styles.dsMsg}>{dsTest.message}</span>
              </p>
              <span className={styles.dsDialogSpacer} />
              <Button onClick={() => setDsDialogOpen(false)}>Cancel</Button>
              <Button type="submit" variant="contained" loading={savingDs}>Save</Button>
            </div>
          </DialogActions>
        </form>
      </Dialog>

      {/* Delete connection: small centred confirm dialog (matches AccountsPage / LivePage) */}
      <Dialog open={!!deleteTarget} onClose={() => setDeleteTarget(null)} fullWidth maxWidth="xs">
        <DialogTitle>Delete connection</DialogTitle>
        <DialogContent sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
          {deleteTarget && (
            <p className={styles.delDialogMsg}>
              Delete <strong>{deleteTarget.name}</strong>?
            </p>
          )}
          <p className={styles.delDialogHint}>
            Panels bound to it fall back to the app database. This cannot be undone.
          </p>
          {deleteError && <Alert severity="error">{deleteError}</Alert>}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setDeleteTarget(null)}>Cancel</Button>
          <Button
            color="error"
            variant="contained"
            loading={deleteMutation.isPending}
            onClick={confirmDeleteDs}
          >
            Delete
          </Button>
        </DialogActions>
      </Dialog>

      <Snackbar
        open={snackbar.open}
        autoHideDuration={4000}
        onClose={() => setSnackbar((s) => ({ ...s, open: false }))}
        anchorOrigin={{ vertical: 'top', horizontal: 'center' }}
      >
        <Alert
          severity={snackbar.severity}
          onClose={() => setSnackbar((s) => ({ ...s, open: false }))}
          sx={{ width: '100%' }}
        >
          {snackbar.message}
        </Alert>
      </Snackbar>
    </div>
  )
}
